/** The word wall: one boxed word, a screen filling with copies of it, then a burst. */

import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";

import { whenWall } from "./schema-conditions";

const wallCost =
  "The wall draws one cached word sprite per grid cell, a few hundred texture draws at most.";

const share = (label: string, defaultValue: number, description: string, target: string, min = 1) => ({
  applicability: whenWall,
  defaultValue,
  description,
  label,
  max: 100,
  min,
  performanceReason: wallCost,
  performanceRole: "responsiveness" as const,
  sliderValueKind: "continuous" as const,
  step: 1,
  target,
  type: "slider" as const,
  unit: "%",
});

export const wallSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "One word appears boxed at the centre, copies of it land whole at random all over the screen until it is full, then the wall blows apart.",
      label: "Show word wall",
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      target: "wall.enabled",
      type: "switch",
    },
    text: {
      applicability: whenWall,
      commitMode: "content",
      defaultValue: "Transparent",
      description: "The word repeated across the wall; the centre copy is boxed.",
      label: "Word",
      performanceReason: "The word is drawn once into a sprite and reused.",
      performanceRole: "responsiveness",
      target: "wall.text",
      textValueKind: "single-line",
      type: "text",
    },
    type: {
      applicability: whenWall,
      defaultValue: {
        color: "#FFFFFF",
        fontId: "ibm-plex-mono",
        fontSize: 28,
        fontWeight: "500",
        letterSpacing: "widest",
        lineHeight: "tight",
        opacity: 100,
        textCase: "original",
      },
      label: "Font",
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      target: "wall.type",
      type: "fontPicker",
    },
    timing: {
      applicability: whenWall,
      defaultValue: "after",
      description: "After: once the code roll, end text and logo finish. At start: from the top of the loop.",
      label: "Starts",
      options: [
        { label: "After", value: "after" },
        { label: "At start", value: "start" },
      ],
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      target: "wall.timing",
      type: "segmented",
    },
    entry: {
      applicability: whenWall,
      defaultValue: "flash",
      description:
        "How each word arrives. Flash lands it as a selected box that snaps back; Pop springs it in; Glitch tears it in with stutters; Plain just appears. Landed words keep flashing now and then until the burst.",
      label: "Arrival",
      options: [
        { label: "Flash", value: "flash" },
        { label: "Pop", value: "pop" },
        { label: "Glitch", value: "glitch" },
        { label: "Plain", value: "plain" },
      ],
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      target: "wall.entry",
      type: "segmented",
    },
    duration: {
      applicability: whenWall,
      defaultValue: 5,
      description: "Seconds the whole wall takes, from the first word to the end of the burst. The loop follows it.",
      label: "Duration",
      max: 30,
      min: 1,
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "wall.duration",
      type: "slider",
      unit: "s",
    },
    hero: share("Hero time", 15, "Share of Duration the boxed centre word stands alone.", "wall.hero"),
    land: share("Land time", 30, "Share of Duration over which the other words land at random.", "wall.land"),
    hold: share("Hold time", 25, "Share of the time before the burst that the full wall holds. Hero, Land and Hold are relative to each other.", "wall.hold", 0),
    burst: {
      applicability: whenWall,
      defaultValue: 1.5,
      description: "Seconds the burst plays out, at the end of Duration (at most 90% of it). Hero, Land and Hold share the rest.",
      label: "Burst time",
      max: 10,
      min: 0.1,
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "wall.burst",
      type: "slider",
      unit: "s",
    },
    force: {
      applicability: whenWall,
      defaultValue: 60,
      description: "How far the burst throws the words, as a share of the frame diagonal.",
      label: "Force",
      max: 300,
      min: 10,
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "wall.force",
      type: "slider",
      unit: "%",
    },
    spin: {
      applicability: whenWall,
      defaultValue: 40,
      description: "How much the words tumble as they fly.",
      label: "Spin",
      max: 100,
      min: 0,
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "wall.spin",
      type: "slider",
      unit: "%",
    },
    colGap: {
      applicability: whenWall,
      defaultValue: 1.5,
      description: "Space between words in a row, in multiples of the font size.",
      label: "Column gap",
      max: 10,
      min: 0,
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "wall.colGap",
      type: "slider",
    },
    rowGap: {
      applicability: whenWall,
      defaultValue: 0.25,
      description: "Extra space between rows, in multiples of the font size.",
      label: "Row gap",
      max: 4,
      min: 0,
      performanceReason: wallCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "wall.rowGap",
      type: "slider",
    },
    cover: {
      applicability: whenWall,
      defaultValue: true,
      description: "Hides the halftone sheet while the wall plays, so only the words show.",
      label: "Clear sheet",
      performanceReason: "Clearing the sheet skips its draw.",
      performanceRole: "responsiveness",
      target: "wall.cover",
      type: "switch",
    },
    blast: {
      applicability: whenWall,
      defaultValue: true,
      description: "Fires the Burst section's explosion under the flying words and brings the sheet back behind them.",
      label: "Sheet blast",
      performanceReason: "One burst's worth of cells while it plays.",
      performanceRole: "responsiveness",
      target: "wall.blast",
      type: "switch",
    },
  },
  id: "wall",
  layoutGroups: [{ columns: 2, controls: ["cover", "blast"], layout: "inline" }],
  title: "Word wall",
};
