/** The code roll and the end text that follows it. */

import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";

import {
  DEFAULT_CODE_BREAK_SECONDS,
  DEFAULT_CODE_PAUSE_SECONDS,
  DEFAULT_CODE_ROLL_SECONDS,
  DEFAULT_CODE_TEXT,
  DEFAULT_END_HOLD_SECONDS,
  DEFAULT_END_TEXT,
  MAX_CODE_PHASE_SECONDS,
  MAX_CODE_SHORT_PHASE_SECONDS,
} from "../engine/engine-code-text";
import { whenCodeRolling, whenEndText } from "./schema-conditions";

export const codeRollSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Your code text takes over the canvas: it rolls through the frame, then breaks apart into tumbling characters that swirl away before the end text.",
      label: "Roll code",
      performanceReason:
        "The roll draws one text line per visible row, and one glyph per breaking character.",
      performanceRole: "responsiveness",
      target: "code.enabled",
      type: "switch",
    },
    text: {
      applicability: whenCodeRolling,
      commitMode: "content",
      defaultValue: DEFAULT_CODE_TEXT,
      description:
        "One terminal line per line. A Tab, or a typed \\t, pushes the rest of that line flush right, for status tags like [ OK ].",
      label: "Code",
      performanceReason:
        "Longer text adds characters to break apart; lines off screen are not drawn.",
      performanceRole: "responsiveness",
      target: "code.text",
      textValueKind: "multiline",
      type: "code",
    },
    motion: {
      applicability: whenCodeRolling,
      defaultValue: "terminal",
      description:
        "Terminal fills lines in from the top and scrolls once the screen is full; Roll up and Roll down move the whole block through the frame.",
      label: "Scroll",
      options: [
        { label: "Terminal", value: "terminal" },
        { label: "Roll up", value: "up" },
        { label: "Roll down", value: "down" },
      ],
      performanceReason: "Scroll changes where lines sit, not how many are drawn.",
      performanceRole: "responsiveness",
      target: "code.motion",
      type: "segmented",
    },
    reveal: {
      applicability: whenCodeRolling,
      defaultValue: "type",
      description:
        "How each line appears: whole, typed on with a cursor, decoded out of scrambled symbols, or landing doubled and flickering like a glitching screen.",
      label: "Reveal",
      options: [
        { label: "Line", value: "line" },
        { label: "Type", value: "type" },
        { label: "Decode", value: "decode" },
        { label: "Glitch", value: "glitch" },
      ],
      performanceReason: "Reveal changes how an arriving line is drawn, not how many lines.",
      performanceRole: "responsiveness",
      target: "code.reveal",
      type: "segmented",
    },
    type: {
      applicability: whenCodeRolling,
      defaultValue: {
        color: "#FFFFFF",
        fontId: "ibm-plex-mono",
        fontSize: 18,
        fontWeight: "500",
        letterSpacing: "normal",
        lineHeight: "tight",
        opacity: 100,
        textCase: "original",
      },
      label: "Font",
      performanceReason: "Typography restyles the same code lines.",
      performanceRole: "responsiveness",
      target: "code.type",
      type: "fontPicker",
    },
    rollTime: {
      applicability: whenCodeRolling,
      defaultValue: DEFAULT_CODE_ROLL_SECONDS,
      description:
        "Seconds for the whole text to arrive. Roll, hold, break and end text play back to back, and the timeline length follows their total.",
      label: "Roll time",
      max: MAX_CODE_PHASE_SECONDS,
      min: 0.5,
      performanceReason: "Roll time changes pacing, not the text drawn.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "code.rollTime",
      type: "slider",
      unit: "s",
    },
    hold: {
      applicability: whenCodeRolling,
      defaultValue: DEFAULT_CODE_PAUSE_SECONDS,
      description: "Seconds the arrived text holds still before it breaks apart.",
      label: "Hold time",
      max: MAX_CODE_SHORT_PHASE_SECONDS,
      min: 0,
      performanceReason: "Hold keeps the same lines up for longer.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "code.hold",
      type: "slider",
      unit: "s",
    },
    breakStyle: {
      applicability: whenCodeRolling,
      defaultValue: "swirl",
      description:
        "How the text comes apart: Swirl streams it away in ribbons, Burst blasts it out from the centre, Vortex drains it into the middle, Fall drops it, Wind sweeps it off to the right, Glitch scrambles it and flickers it out.",
      label: "Break style",
      options: [
        { label: "Swirl", value: "swirl" },
        { label: "Burst", value: "burst" },
        { label: "Vortex", value: "vortex" },
        { label: "Fall", value: "fall" },
        { label: "Wind", value: "wind" },
        { label: "Glitch", value: "glitch" },
      ],
      performanceReason: "Break style changes each character's path, not how many break.",
      performanceRole: "responsiveness",
      target: "code.breakStyle",
      type: "select",
    },
    breakTime: {
      applicability: whenCodeRolling,
      defaultValue: DEFAULT_CODE_BREAK_SECONDS,
      description:
        "How long the break takes, until the last tumbling character has faded.",
      label: "Break time",
      max: MAX_CODE_SHORT_PHASE_SECONDS,
      min: 0.2,
      performanceReason: "Break time spreads the same characters over more frames.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "code.breakTime",
      type: "slider",
      unit: "s",
    },
    sheetAtEnd: {
      applicability: whenCodeRolling,
      defaultValue: false,
      description:
        "Off keeps the canvas clear for the end text, as in a terminal film; on brings the halftone sheet back once the code has broken away.",
      label: "Sheet at end",
      performanceReason:
        "The sheet costs what it does without the roll, and only after the break.",
      performanceRole: "responsiveness",
      target: "code.sheetAtEnd",
      type: "switch",
    },
  },
  id: "code",
  title: "Code roll",
};

export const endTextSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Caption-style text that types on once the code roll has broken away, or from the loop start without it.",
      label: "Show end text",
      performanceReason: "End text is a handful of text draws.",
      performanceRole: "responsiveness",
      target: "endText.enabled",
      type: "switch",
    },
    text: {
      applicability: whenEndText,
      commitMode: "content",
      defaultValue: DEFAULT_END_TEXT,
      description: "One line of end text per line.",
      label: "Lines",
      performanceReason: "Line count changes a handful of text draws.",
      performanceRole: "responsiveness",
      target: "endText.text",
      textValueKind: "multiline",
      type: "code",
    },
    reveal: {
      applicability: whenEndText,
      defaultValue: "type",
      label: "Reveal",
      options: [
        { label: "Type", value: "type" },
        { label: "Decode", value: "decode" },
        { label: "Static", value: "static" },
      ],
      performanceReason: "Reveal changes which characters are drawn, not how many lines.",
      performanceRole: "responsiveness",
      target: "endText.reveal",
      type: "segmented",
    },
    hold: {
      applicability: whenEndText,
      defaultValue: DEFAULT_END_HOLD_SECONDS,
      description:
        "Seconds the end text stays up, from its first character to its exit. The timeline length follows the whole sequence.",
      label: "Hold",
      max: MAX_CODE_PHASE_SECONDS,
      min: 0.5,
      performanceReason: "Hold changes pacing, not the text drawn.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "endText.hold",
      type: "slider",
      unit: "s",
    },
    type: {
      applicability: whenEndText,
      defaultValue: {
        color: "#FFFFFF",
        fontId: "ibm-plex-mono",
        fontSize: 30,
        fontWeight: "600",
        letterSpacing: "normal",
        lineHeight: "tight",
        opacity: 100,
        textCase: "original",
      },
      label: "Font",
      performanceReason: "Typography restyles the same end text lines.",
      performanceRole: "responsiveness",
      target: "endText.type",
      type: "fontPicker",
    },
    position: {
      applicability: whenEndText,
      defaultValue: { x: 0, y: 0 },
      label: "Position",
      performanceReason: "Position moves the end text block, not its size.",
      performanceRole: "responsiveness",
      target: "endText.position",
      type: "vector",
    },
    highlight: {
      applicability: whenEndText,
      commitMode: "content",
      defaultValue: "",
      description:
        "A word set in a solid box with the letters cut out, like selected text. Every occurrence is boxed.",
      label: "Highlight",
      performanceReason: "A highlight adds one box per occurrence.",
      performanceRole: "responsiveness",
      target: "endText.highlight",
      textValueKind: "single-line",
      type: "text",
    },
    blink: {
      applicability: whenEndText,
      defaultValue: true,
      description: "The highlight box and the cursor blink while the end text is up.",
      label: "Blink",
      performanceReason: "Blinking toggles draws that already exist.",
      performanceRole: "responsiveness",
      target: "endText.blink",
      type: "switch",
    },
    cursor: {
      applicability: whenEndText,
      defaultValue: false,
      label: "Cursor",
      performanceReason: "The cursor is one extra character.",
      performanceRole: "responsiveness",
      target: "endText.cursor",
      type: "switch",
    },
  },
  id: "end-text",
  layoutGroups: [
    { columns: 2, controls: ["blink", "cursor"], layout: "inline" },
  ],
  title: "End text",
};
