/** Procedural layers over the sheet: burst rays, the swirl, and the caption. */

import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";

import { MAX_BURST_RAYS, MAX_SWIRL_PARTICLES } from "../engine/engine-constants";
import { whenBursting, whenCaptioned, whenSwirling } from "./schema-conditions";

export const burstSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Rays of characters shoot out from one point and fly off the sheet, each ray drawn in the stroke that matches its angle.",
      label: "Burst effect",
      performanceReason:
        "The burst draws at most the empty cells of the same grid.",
      performanceRole: "responsiveness",
      target: "burst.enabled",
      type: "switch",
    },
    origin: {
      applicability: whenBursting,
      defaultValue: { x: 0, y: 0.55 },
      label: "Origin",
      performanceReason: "Origin moves the ray centre, not the ray count.",
      performanceRole: "responsiveness",
      target: "burst.origin",
      type: "vector",
    },
    rays: {
      applicability: whenBursting,
      defaultValue: 14,
      label: "Rays",
      max: MAX_BURST_RAYS,
      min: 3,
      performanceReason:
        "Ray count is bounded by the grid; every cell tests one ray.",
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "burst.rays",
      type: "slider",
      variant: "discrete",
    },
    reach: {
      applicability: whenBursting,
      defaultValue: 90,
      description: "How far the rays fly, as a share of the sheet diagonal.",
      label: "Reach",
      max: 150,
      min: 10,
      performanceReason: "Reach lengthens rays within the same grid.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      target: "burst.reach",
      type: "slider",
      unit: "%",
    },
    thickness: {
      applicability: whenBursting,
      defaultValue: 1.2,
      description: "Ray width, measured in grid cells.",
      label: "Thickness",
      max: 4,
      min: 0.5,
      performanceReason: "Thickness widens rays within the same grid.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "burst.thickness",
      type: "slider",
    },
    count: {
      applicability: whenBursting,
      defaultValue: 1,
      description: "Whole bursts inside one timeline loop.",
      label: "Bursts",
      max: 4,
      min: 1,
      performanceReason: "Burst count changes timing, not the drawn cell count.",
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "burst.count",
      type: "slider",
      variant: "discrete",
    },
  },
  id: "burst",
  title: "Burst",
};

export const swirlSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Streams of binary and arrow characters orbit a centre on spiral arms, each turned to face along its path.",
      label: "Swirl effect",
      performanceReason:
        "The swirl adds a bounded set of glyphs beside the grid.",
      performanceRole: "responsiveness",
      target: "swirl.enabled",
      type: "switch",
    },
    center: {
      applicability: whenSwirling,
      defaultValue: { x: 0, y: 0 },
      label: "Center",
      performanceReason: "Center moves the orbit, not the particle count.",
      performanceRole: "responsiveness",
      target: "swirl.center",
      type: "vector",
    },
    count: {
      applicability: whenSwirling,
      defaultValue: 240,
      label: "Particles",
      max: MAX_SWIRL_PARTICLES,
      min: 20,
      performanceReason:
        "Particles are capped at a few hundred glyphs, a constant add-on beside the grid.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "swirl.count",
      type: "slider",
    },
    radius: {
      applicability: whenSwirling,
      defaultValue: 42,
      description: "Orbit radius as a share of the shorter side of the sheet.",
      label: "Radius",
      max: 100,
      min: 5,
      performanceReason: "Radius moves particles, not their count.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      target: "swirl.radius",
      type: "slider",
      unit: "%",
    },
    band: {
      applicability: whenSwirling,
      defaultValue: 50,
      description: "How wide the ring of streams is.",
      label: "Band",
      max: 100,
      min: 0,
      performanceReason: "Band spreads particles, not their count.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      target: "swirl.band",
      type: "slider",
      unit: "%",
    },
    turns: {
      applicability: whenSwirling,
      defaultValue: 1,
      description: "Whole turns per timeline loop, so the stream closes on itself.",
      label: "Turns",
      max: 4,
      min: 1,
      performanceReason: "Turns change orbit speed, not the particle count.",
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "swirl.turns",
      type: "slider",
      variant: "discrete",
    },
  },
  id: "swirl",
  title: "Swirl",
};

export const captionSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Terminal-style text set crisply over the sheet; each line types on, decodes or holds.",
      label: "Caption text",
      performanceReason:
        "A caption is a handful of text draws above the grid.",
      performanceRole: "responsiveness",
      target: "caption.enabled",
      type: "switch",
    },
    text: {
      applicability: whenCaptioned,
      commitMode: "content",
      defaultValue: "System > Updated",
      description: "One caption line per line of text.",
      label: "Lines",
      performanceReason:
        "Line count changes a handful of text draws, not the grid.",
      performanceRole: "responsiveness",
      target: "caption.text",
      textValueKind: "multiline",
      type: "code",
    },
    reveal: {
      applicability: whenCaptioned,
      defaultValue: "type",
      label: "Reveal",
      options: [
        { label: "Type", value: "type" },
        { label: "Decode", value: "decode" },
        { label: "Static", value: "static" },
      ],
      performanceReason:
        "Reveal changes which characters are drawn, not how many lines.",
      performanceRole: "responsiveness",
      target: "caption.reveal",
      type: "segmented",
    },
    type: {
      applicability: whenCaptioned,
      defaultValue: {
        color: "#FFFFFF",
        fontId: "ibm-plex-mono",
        fontSize: 30,
        fontWeight: "600",
        letterSpacing: "normal",
        lineHeight: "tight",
        opacity: 100,
        textCase: "original",
      },
      label: "Font",
      performanceReason:
        "Typography restyles the same caption lines.",
      performanceRole: "responsiveness",
      target: "caption.type",
      type: "fontPicker",
    },
    position: {
      applicability: whenCaptioned,
      defaultValue: { x: 0, y: 0 },
      label: "Position",
      performanceReason: "Position moves the caption block, not its size.",
      performanceRole: "responsiveness",
      target: "caption.position",
      type: "vector",
    },
    highlight: {
      applicability: whenCaptioned,
      commitMode: "content",
      defaultValue: "",
      description:
        "A word to set in a solid box with the letters cut out, like selected text. Every occurrence is boxed.",
      label: "Highlight",
      performanceReason: "A highlight adds one box per occurrence.",
      performanceRole: "responsiveness",
      target: "caption.highlight",
      textValueKind: "single-line",
      type: "text",
    },
    blink: {
      applicability: whenCaptioned,
      defaultValue: true,
      description: "The highlight box and the cursor blink in time with the loop.",
      label: "Blink",
      performanceReason: "Blinking toggles draws that already exist.",
      performanceRole: "responsiveness",
      target: "caption.blink",
      type: "switch",
    },
    cursor: {
      applicability: whenCaptioned,
      defaultValue: false,
      label: "Cursor",
      performanceReason: "The cursor is one extra character.",
      performanceRole: "responsiveness",
      target: "caption.cursor",
      type: "switch",
    },
  },
  id: "caption",
  layoutGroups: [
    { columns: 2, controls: ["blink", "cursor"], layout: "inline" },
  ],
  title: "Caption",
};
