/** The data text labels and the glitch fillers that hide the cuts between scenes. */

import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";

import { DEFAULT_DATA_BOX, DEFAULT_DATA_ITEMS } from "../engine/engine-datatext";
import {
  MAX_TRANSITION_BLOCKS,
  MAX_TRANSITION_SECONDS,
  MIN_TRANSITION_BLOCKS,
  MIN_TRANSITION_SECONDS,
} from "../engine/engine-transition";
import { whenData, whenTransition, whenTransitionOnBeats } from "./schema-conditions";

const dataCost = "Data text draws a few dozen short labels and marks; only characters mid-reveal draw one by one.";
const fillerCost =
  "A filler draws only while one is on screen: a few batched fills and one small bloom texture per frame.";

export const dataTextSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Small monospace labels decode on one after another at different places on a strict grid, with square markers, rules that grow into stepped bars, a wide wordmark and a boxed status tag, then leave. With music, beats refresh the data.",
      label: "Show data text",
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.enabled",
      type: "switch",
    },
    items: {
      addLabel: "Add item",
      applicability: whenData,
      defaultValue: DEFAULT_DATA_ITEMS,
      description:
        "Each item has its own text, style, place, size and delay, so different text sits at different places. A | in the text starts a second line. Items appear in list order, Stagger apart.",
      hardMaxItems: 24,
      itemControls: {
        text: {
          defaultValue: "NEW LABEL",
          label: "Text",
          performanceReason: dataCost,
          performanceRole: "responsiveness",
          type: "text",
        },
        style: {
          defaultValue: "label",
          label: "Style",
          options: [
            { label: "Label", value: "label" },
            { label: "Bullet", value: "bullet" },
            { label: "Wordmark", value: "wordmark" },
            { label: "Boxed", value: "boxed" },
          ],
          performanceReason: dataCost,
          performanceRole: "responsiveness",
          type: "select",
        },
        position: {
          defaultValue: { x: 0, y: 0 },
          label: "Position",
          performanceReason: dataCost,
          performanceRole: "responsiveness",
          type: "vector",
        },
        size: {
          defaultValue: 16,
          label: "Size",
          max: 160,
          min: 8,
          performanceReason: dataCost,
          performanceRole: "responsiveness",
          step: 1,
          type: "slider",
          unit: "px",
        },
        delay: {
          defaultValue: 0,
          label: "Delay",
          max: 10,
          min: 0,
          performanceReason: dataCost,
          performanceRole: "responsiveness",
          step: 0.05,
          type: "slider",
          unit: "s",
        },
      },
      itemLabel: "Item",
      label: "Items",
      minItems: 1,
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      removeLabel: "Remove item",
      selectionTarget: "data.selected",
      target: "data.items",
      type: "collectionActions",
    },
    type: {
      applicability: whenData,
      defaultValue: {
        color: "#FF2A2A",
        fontId: "ibm-plex-mono",
        fontSize: 16,
        fontWeight: "600",
        letterSpacing: "wide",
        lineHeight: "tight",
        opacity: 100,
        textCase: "uppercase",
      },
      label: "Font",
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.type",
      type: "fontPicker",
    },
    reveal: {
      applicability: whenData,
      defaultValue: "decode",
      description:
        "Decode resolves each character out of scrambled ones of the same kind; Type runs a block caret; Flicker stutters on like a failing tube. Wordmarks assemble letter by letter from fragments.",
      label: "Reveal",
      options: [
        { label: "Decode", value: "decode" },
        { label: "Type", value: "type" },
        { label: "Flicker", value: "flicker" },
      ],
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.reveal",
      type: "segmented",
    },
    exit: {
      applicability: whenData,
      defaultValue: "decode",
      description:
        "Decode clears each item from its end through noise; Bullet backspaces it into a square that blinks twice; Cut drops everything at once after the last item has held; Stay keeps it to the loop end.",
      label: "Departure",
      options: [
        { label: "Decode", value: "decode" },
        { label: "Bullet", value: "bullet" },
        { label: "Cut", value: "cut" },
        { label: "Stay", value: "stay" },
      ],
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.exit",
      type: "segmented",
    },
    timing: {
      applicability: whenData,
      defaultValue: "after",
      description:
        "After waits until the code roll, end text and logo have finished; With logo starts as the logo starts, to frame it; At start begins at the top of the loop.",
      label: "Starts",
      options: [
        { label: "After", value: "after" },
        { label: "With logo", value: "logo" },
        { label: "At start", value: "start" },
      ],
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.timing",
      type: "segmented",
    },
    start: {
      applicability: whenData,
      defaultValue: 0.2,
      description: "Seconds after the start point before the first item appears.",
      label: "Start delay",
      max: 20,
      min: 0,
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "data.start",
      type: "slider",
      unit: "s",
    },
    stagger: {
      applicability: whenData,
      defaultValue: 0.12,
      description: "Seconds between one item starting and the next, in list order.",
      label: "Stagger",
      max: 2,
      min: 0,
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "data.stagger",
      type: "slider",
      unit: "s",
    },
    hold: {
      applicability: whenData,
      defaultValue: 1.8,
      description: "Seconds the whole block holds once its last item is in; it shortens so the loop ends on an empty frame.",
      label: "Hold",
      max: 20,
      min: 0,
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "data.hold",
      type: "slider",
      unit: "s",
    },
    repeat: {
      applicability: whenData,
      defaultValue: false,
      description: "Tiles whole copies of the block up and down the frame, like the reference's stacked label sheets.",
      label: "Tile block",
      performanceReason: "Each copy draws the same labels again.",
      performanceRole: "responsiveness",
      target: "data.repeat",
      type: "switch",
    },
    box: {
      applicability: whenData,
      defaultValue: DEFAULT_DATA_BOX,
      description: "Fill of Boxed items; their text turns dark or light to suit.",
      label: "Box",
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.box",
      type: "color",
    },
    markers: {
      applicability: whenData,
      defaultValue: true,
      description:
        "Square registration markers in pairs and singles on the column grid, two rows at the top of the frame and two at the bottom. With music they count the beats and twinkle with the highs.",
      label: "Markers",
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.markers",
      type: "switch",
    },
    rules: {
      applicability: whenData,
      defaultValue: true,
      description:
        "Thin rules above and below the block grow out of a square and thicken into stepped bars. With music the bars jump on beats and stretch with the bass.",
      label: "Rules",
      performanceReason: dataCost,
      performanceRole: "responsiveness",
      target: "data.rules",
      type: "switch",
    },
  },
  id: "data",
  layoutGroups: [{ columns: 2, controls: ["markers", "rules"], layout: "inline" }],
  title: "Data text",
};

export const transitionSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Hides each cut behind a short glitch filler: it covers the frame, holds it dark with a faint grid and glints while the shot changes, then uncovers the next shot.",
      label: "Glitch filler",
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      target: "transition.enabled",
      type: "switch",
    },
    style: {
      applicability: whenTransition,
      defaultValue: "glow",
      description:
        "Glow: a stepped dome of hot pixels in a soft bloom sweeps through. Mosaic: the frame breaks into cooling pixels. Slice: the picture tears as dark slabs slam in. Scan: a CRT beam shuts the picture off line by line. Grid wipe: a halftone of squares grows closed.",
      label: "Style",
      options: [
        { label: "Glow", value: "glow" },
        { label: "Mosaic", value: "mosaic" },
        { label: "Slice", value: "slice" },
        { label: "Scan", value: "scan" },
        { label: "Grid wipe", value: "grid" },
      ],
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      target: "transition.style",
      type: "select",
    },
    placement: {
      applicability: whenTransition,
      defaultValue: "both",
      description:
        "Cuts: between the code roll, end text, data text and logo. Seam: across the loop's end and start, so clips cut together seamlessly. Both: cuts and seam. Beats: dips the shot on every strong beat instead, with Audio reactive on.",
      label: "Placement",
      options: [
        { label: "Cuts", value: "cuts" },
        { label: "Seam", value: "loop" },
        { label: "Both", value: "both" },
        { label: "Beats", value: "beats" },
      ],
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      target: "transition.placement",
      type: "segmented",
    },
    threshold: {
      applicability: whenTransitionOnBeats,
      defaultValue: 80,
      description: "How strong a beat must be to fire a filler; raise it for fewer, bigger hits.",
      label: "Beat threshold",
      max: 100,
      min: 0,
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "transition.threshold",
      type: "slider",
      unit: "%",
    },
    direction: {
      applicability: whenTransition,
      defaultValue: "up",
      description: "Which way the filler travels across the frame.",
      label: "Direction",
      options: [
        { label: "Up", value: "up" },
        { label: "Down", value: "down" },
        { label: "Left", value: "left" },
        { label: "Right", value: "right" },
      ],
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      target: "transition.direction",
      type: "segmented",
    },
    duration: {
      applicability: whenTransition,
      defaultValue: 0.8,
      description: "Seconds from the first covered frame to the last. A beat filler flares in on the hit and uncovers in half this.",
      label: "Duration",
      max: MAX_TRANSITION_SECONDS,
      min: MIN_TRANSITION_SECONDS,
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "transition.duration",
      type: "slider",
      unit: "s",
    },
    hold: {
      applicability: whenTransition,
      defaultValue: 20,
      description: "Share of the filler the frame stays fully covered around the cut.",
      label: "Hold",
      max: 60,
      min: 0,
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "transition.hold",
      type: "slider",
      unit: "%",
    },
    intensity: {
      applicability: whenTransition,
      defaultValue: 85,
      description: "Light, sparks and tearing: the bloom, hot pixels, glints and grain.",
      label: "Intensity",
      max: 100,
      min: 0,
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "transition.intensity",
      type: "slider",
      unit: "%",
    },
    blocks: {
      applicability: whenTransition,
      defaultValue: 6,
      description: "Grid pixels across the frame's shorter side; fewer means bigger, chunkier blocks.",
      label: "Blocks",
      max: MAX_TRANSITION_BLOCKS,
      min: MIN_TRANSITION_BLOCKS,
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "transition.blocks",
      type: "slider",
      variant: "discrete",
    },
    color: {
      applicability: whenTransition,
      defaultValue: "#FFFFFF",
      description: "Colour of the light; its white-hot core is mixed from it.",
      label: "Glow color",
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      semanticGroup: "filler-colors",
      target: "transition.color",
      type: "color",
    },
    fill: {
      applicability: whenTransition,
      defaultValue: "#050406",
      description: "Colour of the dark the filler holds.",
      label: "Cover color",
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      semanticGroup: "filler-colors",
      target: "transition.fill",
      type: "color",
    },
    cover: {
      applicability: whenTransition,
      defaultValue: 100,
      description: "Opacity of the dark at full strength; lower lets the shot show through the hold.",
      label: "Cover opacity",
      max: 100,
      min: 0,
      performanceReason: fillerCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "transition.cover",
      type: "slider",
      unit: "%",
    },
  },
  id: "transition",
  title: "Transition",
};
