/** Text bars that fly through the frame, and the logo reveal. */

import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";

import { BAR_ENTER_OPTIONS, BAR_EXIT_OPTIONS, DEFAULT_BAR_ITEMS } from "../engine/engine-bars";
import { whenBars, whenLogo, whenLogoTinted } from "./schema-conditions";

export const barsSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Short labels in a solid box with the letters cut out come in one at a time, hold, and leave, each with its own animation.",
      label: "Show bars",
      performanceReason: "One bar is drawn at a time, a box and a few characters.",
      performanceRole: "responsiveness",
      target: "bars.enabled",
      type: "switch",
    },
    items: {
      addLabel: "Add bar",
      applicability: whenBars,
      defaultValue: DEFAULT_BAR_ITEMS,
      description:
        "Each bar has its own text, entrance and departure, and they take turns through the loop.",
      hardMaxItems: 12,
      itemControls: {
        text: {
          defaultValue: "NEW BAR",
          label: "Text",
          performanceReason: "A bar's text is a few characters in one box.",
          performanceRole: "responsiveness",
          type: "text",
        },
        enter: {
          defaultValue: "left",
          label: "Entrance",
          options: BAR_ENTER_OPTIONS,
          performanceReason: "Entrance changes how the same bar moves in.",
          performanceRole: "responsiveness",
          type: "select",
        },
        exit: {
          defaultValue: "bulletRight",
          label: "Departure",
          options: BAR_EXIT_OPTIONS,
          performanceReason: "Departure changes how the same bar moves out.",
          performanceRole: "responsiveness",
          type: "select",
        },
      },
      itemLabel: "Bar",
      label: "Bars",
      minItems: 1,
      performanceReason: "More bars change which bar shows, not how many draw at once.",
      performanceRole: "responsiveness",
      removeLabel: "Remove bar",
      selectionTarget: "bars.selected",
      target: "bars.items",
      type: "collectionActions",
    },
    style: {
      applicability: whenBars,
      defaultValue: "box",
      label: "Style",
      options: [
        { label: "Box", value: "box" },
        { label: "Pill", value: "capsule" },
        { label: "Frame", value: "outline" },
        { label: "Text", value: "text" },
      ],
      performanceReason: "Style changes one shape per bar.",
      performanceRole: "responsiveness",
      target: "bars.style",
      type: "segmented",
    },
    type: {
      applicability: whenBars,
      defaultValue: {
        color: "#FFFFFF",
        fontId: "ibm-plex-mono",
        fontSize: 26,
        fontWeight: "600",
        letterSpacing: "normal",
        lineHeight: "tight",
        opacity: 100,
        textCase: "original",
      },
      label: "Font",
      performanceReason: "Typography restyles the same bar.",
      performanceRole: "responsiveness",
      target: "bars.type",
      type: "fontPicker",
    },
    position: {
      applicability: whenBars,
      defaultValue: { x: 0, y: 0.72 },
      label: "Position",
      performanceReason: "Position moves the bar, not its size.",
      performanceRole: "responsiveness",
      target: "bars.position",
      type: "vector",
    },
    scatter: {
      applicability: whenBars,
      defaultValue: 30,
      description: "How far each bar strays from Position, so they land in different places.",
      label: "Scatter",
      max: 100,
      min: 0,
      performanceReason: "Scatter moves bars, not how many draw.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      target: "bars.scatter",
      type: "slider",
      unit: "%",
    },
    time: {
      applicability: whenBars,
      defaultValue: 1.8,
      description:
        "Seconds each bar is on screen, from coming in to gone; bars fit the loop exactly.",
      label: "Bar time",
      max: 20,
      min: 0.5,
      performanceReason: "Bar time changes pacing, not the bar drawn.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "bars.time",
      type: "slider",
      unit: "s",
    },
    hold: {
      applicability: whenBars,
      defaultValue: 55,
      description: "Share of each bar's time it holds still between coming in and leaving.",
      label: "Hold",
      max: 90,
      min: 10,
      performanceReason: "Hold changes pacing, not the bar drawn.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      target: "bars.hold",
      type: "slider",
      unit: "%",
    },
  },
  id: "bars",
  title: "Text bars",
};

export const logoSection: ToolcraftControlSectionSchema = {
  controls: {
    enabled: {
      applicability: { mode: "always" },
      defaultValue: false,
      description:
        "Your logo assembles out of pieces, by default flying in through a moving 3D camera, locks into its crisp form with a flash, holds, and can leave again. Logo build sets how it assembles.",
      label: "Reveal logo",
      performanceReason: "The logo is a grid of blocks built once per upload and size.",
      performanceRole: "responsiveness",
      target: "logo.enabled",
      type: "switch",
    },
    file: {
      accept: ".png,.jpg,.jpeg,.webp,.svg,image/png,image/jpeg,image/webp,image/svg+xml",
      applicability: whenLogo,
      assetKind: "file",
      label: "Logo",
      performanceReason: "The logo is decoded once and cut into blocks once per size.",
      performanceRole: "responsiveness",
      target: "logo.file",
      type: "fileDrop",
    },
    exit: {
      applicability: whenLogo,
      defaultValue: "hold",
      description:
        "Stay until the loop ends, shatter into flying blocks, disassemble in reverse, glitch out in chunks, or switch off like an old tube.",
      label: "Departure",
      options: [
        { label: "Stay", value: "hold" },
        { label: "Shatter", value: "shatter" },
        { label: "Reverse", value: "reverse" },
        { label: "Glitch out", value: "glitch" },
        { label: "Switch off", value: "collapse" },
      ],
      performanceReason: "Departure changes how the same blocks leave.",
      performanceRole: "responsiveness",
      target: "logo.exit",
      type: "select",
    },
    timing: {
      applicability: whenLogo,
      defaultValue: "after",
      description:
        "After starts the reveal once the code roll and end text have finished; At start begins it at the top of the loop.",
      label: "Starts",
      options: [
        { label: "After", value: "after" },
        { label: "At start", value: "start" },
      ],
      performanceReason: "Timing moves the reveal, not its cost.",
      performanceRole: "responsiveness",
      target: "logo.timing",
      type: "segmented",
    },
    delay: {
      applicability: whenLogo,
      defaultValue: 0.2,
      description: "Seconds to wait before the blocks start moving.",
      label: "Delay",
      max: 20,
      min: 0,
      performanceReason: "Delay moves the reveal in time.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "logo.delay",
      type: "slider",
      unit: "s",
    },
    build: {
      applicability: whenLogo,
      defaultValue: 2.8,
      description: "Seconds the logo takes to assemble. The timeline length follows the whole reveal.",
      label: "Build time",
      max: 20,
      min: 0.3,
      performanceReason: "Build time changes pacing, not the blocks drawn.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "logo.build",
      type: "slider",
      unit: "s",
    },
    hold: {
      applicability: whenLogo,
      defaultValue: 2.5,
      description: "Seconds the finished logo holds before it leaves.",
      label: "Hold",
      max: 20,
      min: 0,
      performanceReason: "Hold changes pacing, not the logo drawn.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "logo.hold",
      type: "slider",
      unit: "s",
    },
    size: {
      applicability: whenLogo,
      defaultValue: 45,
      description: "Width of the logo as a share of the frame.",
      label: "Size",
      max: 100,
      min: 10,
      performanceReason: "A larger logo is cut into more blocks at the same block size.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      target: "logo.size",
      type: "slider",
      unit: "%",
    },
    position: {
      applicability: whenLogo,
      defaultValue: { x: 0, y: 0 },
      label: "Position",
      performanceReason: "Position moves the logo, not its size.",
      performanceRole: "responsiveness",
      target: "logo.position",
      type: "vector",
    },
    block: {
      applicability: whenLogo,
      defaultValue: 12,
      description: "Size of each assembling block; smaller blocks mean more of them and a finer build.",
      label: "Block size",
      max: 48,
      min: 4,
      performanceReason: "Smaller blocks cut the logo into more pieces to draw.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 1,
      target: "logo.block",
      type: "slider",
      unit: "px",
    },
    tint: {
      applicability: whenLogo,
      defaultValue: true,
      description:
        "On sets the logo in one ink as a solid silhouette, like the rest of a terminal film; off keeps its own colours and inner detail.",
      label: "Tint",
      performanceReason: "Tinting recolours the same blocks.",
      performanceRole: "responsiveness",
      target: "logo.tint",
      type: "switch",
    },
    ink: {
      applicability: whenLogoTinted,
      defaultValue: "#FFFFFF",
      label: "Ink",
      performanceReason: "Ink changes one colour.",
      performanceRole: "responsiveness",
      target: "logo.ink",
      type: "color",
    },
    hud: {
      applicability: whenLogo,
      defaultValue: true,
      description:
        "Corner brackets open out around the logo, with a counter and a striped progress bar while it builds and a status line once it locks.",
      label: "HUD",
      performanceReason: "The HUD is a few lines and a label.",
      performanceRole: "responsiveness",
      target: "logo.hud",
      type: "switch",
    },
  },
  id: "logo",
  title: "Logo reveal",
};

const logoCost = "The logo is a grid of blocks built once per upload and size; a frame draws each block once.";
const cinematicOnly = { all: [{ equals: "cinematic", target: "logo.style" }], mode: "conditional" } as const;

export const logoBuildSection: ToolcraftControlSectionSchema = {
  controls: {
    style: {
      applicability: { mode: "always" },
      defaultValue: "cinematic",
      description:
        "Cinematic flies the logo's pieces in through a moving 3D camera and docks them with impacts; Dot matrix grows it from one point as twinkling LED dots; Fly in, Build, Scan, Glitch, Sort, Barcode and Swarm are flat builds.",
      label: "Assembly",
      options: [
        { label: "Cinematic", value: "cinematic" },
        { label: "Dot matrix", value: "dots" },
        { label: "Fly in", value: "fly" },
        { label: "Build", value: "build" },
        { label: "Scan", value: "scan" },
        { label: "Glitch", value: "glitch" },
        { label: "Sort", value: "sort" },
        { label: "Barcode", value: "barcode" },
        { label: "Swarm", value: "swarm" },
      ],
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      target: "logo.style",
      type: "select",
    },
    camera: {
      applicability: cinematicOnly,
      defaultValue: "cuts",
      description:
        "Cuts plays a low close pass, a high side angle, then a whip to the front; Orbit swings in from a steep side angle; Fly-through rushes in from far away; Front pushes in square on.",
      label: "Camera",
      options: [
        { label: "Cuts", value: "cuts" },
        { label: "Orbit", value: "orbit" },
        { label: "Fly-through", value: "fly" },
        { label: "Front", value: "front" },
      ],
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      target: "logo.camera",
      type: "select",
    },
    swing: {
      applicability: cinematicOnly,
      defaultValue: 100,
      description: "How far the camera turns away from square on while the logo builds.",
      label: "Angle swing",
      max: 150,
      min: 0,
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 5,
      target: "logo.swing",
      type: "slider",
      unit: "%",
    },
    depth: {
      applicability: cinematicOnly,
      defaultValue: 250,
      description: "How deep each block is extruded, as a share of the block size.",
      label: "Depth",
      max: 600,
      min: 0,
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 10,
      target: "logo.depth",
      type: "slider",
      unit: "%",
    },
    impact: {
      applicability: cinematicOnly,
      defaultValue: 70,
      description: "Strength of each docking hit and of the lock: flash, shake, shockwave, sparks, cut glitches and the lock punch.",
      label: "Impact",
      max: 100,
      min: 0,
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: 5,
      target: "logo.impact",
      type: "slider",
      unit: "%",
    },
    parts: {
      applicability: { all: [{ oneOf: ["cinematic", "dots"], target: "logo.style" }], mode: "conditional" },
      defaultValue: 7,
      description: "How many pieces the logo is cut into; each flies in and docks on its own.",
      label: "Pieces",
      max: 16,
      min: 2,
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      sliderValueKind: "discrete",
      step: 1,
      target: "logo.parts",
      type: "slider",
      variant: "discrete",
    },
    particle: {
      applicability: {
        all: [{ oneOf: ["cinematic", "fly", "build", "scan", "glitch", "sort", "barcode", "swarm"], target: "logo.style" }],
        mode: "conditional",
      },
      defaultValue: "blocks",
      description:
        "What the logo is built from while it assembles: blocks, dots, dashes, glyphs, plus signs, boxed squares, or Morph, where each cell turns from a dash into a dot, a box and then a block as it lands.",
      label: "Particles",
      options: [
        { label: "Blocks", value: "blocks" },
        { label: "Dots", value: "dots" },
        { label: "Dashes", value: "dashes" },
        { label: "Glyphs", value: "glyphs" },
        { label: "Plus", value: "plus" },
        { label: "Boxed", value: "boxed" },
        { label: "Morph", value: "mixed" },
      ],
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      target: "logo.particle",
      type: "select",
    },
    floor: {
      applicability: cinematicOnly,
      defaultValue: true,
      description: "A perspective grid floor that turns with the camera.",
      label: "Floor grid",
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      target: "logo.floor",
      type: "switch",
    },
    streaks: {
      applicability: cinematicOnly,
      defaultValue: true,
      description: "Debris cubes and speed streaks rush past the camera.",
      label: "Debris",
      performanceReason: logoCost,
      performanceRole: "responsiveness",
      target: "logo.streaks",
      type: "switch",
    },
  },
  id: "logo-build",
  layoutGroups: [{ columns: 2, controls: ["floor", "streaks"], layout: "inline" }],
  title: "Logo build",
};
