/** Acceptance rows for the procedural layers: the terminal look, glyph type, the idle field, burst, swirl and caption. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { engineTargets } from "../engine/engine-settings";
import { controlBrowser } from "./acceptance-browser";

const glyphFixture = "wordmark source with the glyph unit selected";

export const layerAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    actionCoverage: ["glyph.terminal"],
    automated: true,
    automatedTestName: "declares the terminal look command",
    browser: controlBrowser("browser: terminal look sets the glyph-film style in one step"),
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable:
      "One press switches to white monospaced glyphs on a character grid over saturated blue, boxes the brightest cells and fills the empty cells with a quiet field, as one undoable step.",
    fixture: "wordmark source at default settings",
    id: "glyph.terminal",
    kind: "control",
    target: "glyph.terminal",
    userAction: "Press Terminal look, then undo.",
  },
  {
    automated: true,
    automatedTestName: "declares the glyph phrase text",
    browser: controlBrowser("browser: a phrase spells itself through the glyph cells"),
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Typing a phrase makes the drawn cells spell it in reading order instead of the ramp; clearing it returns to the ramp.",
    fixture: glyphFixture,
    id: "glyph.phrase",
    kind: "control",
    target: engineTargets.glyphPhrase,
    userAction: "Type a phrase, then clear it.",
  },
  {
    automated: true,
    automatedTestName: "declares the glyph sizing selector",
    browser: controlBrowser("browser: sizing switches between type size and tone size"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Fixed sets every character at one size so tone picks the character and dark cells stay blank; Tone scales each character with its ink.",
    fixture: glyphFixture,
    id: "glyph.sizing",
    kind: "control",
    optionCoverage: ["fixed", "tone"],
    target: engineTargets.glyphSizing,
    userAction: "Select each option of the Sizing segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the glyph face selector",
    browser: controlBrowser("browser: face changes the glyph typeface"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Mono, Sans and Serif each set the characters in a visibly different typeface.",
    fixture: glyphFixture,
    id: "glyph.face",
    kind: "control",
    optionCoverage: ["mono", "sans", "serif"],
    target: engineTargets.glyphFace,
    userAction: "Select each option of the Face segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the glyph weight switch",
    browser: controlBrowser("browser: bold thickens every glyph"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable: "Turning Bold off draws every character at regular weight.",
    fixture: glyphFixture,
    id: "glyph.bold",
    kind: "control",
    target: engineTargets.glyphBold,
    userAction: "Toggle Bold.",
  },
  {
    automated: true,
    automatedTestName: "declares the idle field switch",
    browser: controlBrowser("browser: the idle field fills empty cells with quiet marks"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Turning the idle field on fills the empty cells with dots, dashes and arrows, or small dots for shape units, held clear of the subject, and reveals the field settings.",
    fixture: glyphFixture,
    id: "field.enabled",
    kind: "control",
    target: engineTargets.backdropOn,
    userAction: "Turn Idle field on.",
  },
  {
    automated: true,
    automatedTestName: "declares the field density slider",
    browser: controlBrowser("browser: density fills empty cells with a quiet field"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Density puts a mark in more of the empty cells.",
    fixture: "wordmark source with the idle field on",
    id: "field.density",
    kind: "control",
    target: engineTargets.backdropDensity,
    timelineCoverage: "keyframes",
    userAction: "Lower Density, then raise it.",
  },
  {
    automated: true,
    automatedTestName: "declares the field clearance slider",
    browser: controlBrowser("browser: clearance keeps a margin around the subject"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Clearance widens the empty margin between the subject and the idle field.",
    fixture: "wordmark source with the idle field on",
    id: "field.clearance",
    kind: "control",
    target: engineTargets.backdropClearance,
    timelineCoverage: "keyframes",
    userAction: "Raise Clearance.",
  },
  {
    automated: true,
    automatedTestName: "declares the field opacity slider",
    browser: controlBrowser("browser: opacity dims the idle field"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Lowering Opacity fades the idle field without touching the subject.",
    fixture: "wordmark source with the idle field on",
    id: "field.opacity",
    kind: "control",
    target: engineTargets.backdropOpacity,
    timelineCoverage: "keyframes",
    userAction: "Lower Opacity.",
  },
  {
    automated: true,
    automatedTestName: "declares the burst switch",
    browser: controlBrowser("browser: the burst throws rays of characters"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning the burst on throws rays of angle-matched characters out from the origin over the loop and reveals the burst settings.",
    fixture: "wordmark source at default settings",
    id: "burst.enabled",
    kind: "control",
    target: engineTargets.burstOn,
    userAction: "Turn Burst effect on and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the burst origin vector",
    browser: controlBrowser("browser: origin moves the centre of the burst"),
    componentType: "vector",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Dragging Origin moves the point the rays leave from in the same screen direction.",
    fixture: "wordmark source with the burst on",
    id: "burst.origin",
    kind: "control",
    target: engineTargets.burstOrigin,
    timelineCoverage: "keyframes",
    userAction: "Drag the Origin pad right, then down.",
  },
  {
    automated: true,
    automatedTestName: "declares the burst ray count",
    browser: controlBrowser("browser: rays sets how many lines the burst throws"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Rays throws more, closer lines from the origin.",
    fixture: "wordmark source with the burst on",
    id: "burst.rays",
    kind: "control",
    target: engineTargets.burstRays,
    timelineCoverage: "keyframes",
    userAction: "Raise Rays.",
  },
  {
    automated: true,
    automatedTestName: "declares the burst reach slider",
    browser: controlBrowser("browser: reach sets how far the rays fly"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Reach lets the rays fly further across the sheet.",
    fixture: "wordmark source with the burst on",
    id: "burst.reach",
    kind: "control",
    target: engineTargets.burstReach,
    timelineCoverage: "keyframes",
    userAction: "Raise Reach.",
  },
  {
    automated: true,
    automatedTestName: "declares the burst thickness slider",
    browser: controlBrowser("browser: thickness widens each ray"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Thickness makes each ray several cells wide.",
    fixture: "wordmark source with the burst on",
    id: "burst.thickness",
    kind: "control",
    target: engineTargets.burstThickness,
    timelineCoverage: "keyframes",
    userAction: "Raise Thickness.",
  },
  {
    automated: true,
    automatedTestName: "declares the burst count slider",
    browser: controlBrowser("browser: bursts repeats the burst inside one loop"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Bursts fires the rays that many times inside one loop.",
    fixture: "wordmark source with the burst on",
    id: "burst.count",
    kind: "control",
    target: engineTargets.burstCount,
    timelineCoverage: "keyframes",
    userAction: "Raise Bursts and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the swirl switch",
    browser: controlBrowser("browser: the swirl orbits streams of characters"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning the swirl on sends streams of binary and arrow characters around the centre, each facing along its path, and reveals the swirl settings.",
    fixture: "wordmark source at default settings",
    id: "swirl.enabled",
    kind: "control",
    target: engineTargets.swirlOn,
    userAction: "Turn Swirl effect on and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the swirl center vector",
    browser: controlBrowser("browser: center moves the orbit"),
    componentType: "vector",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable: "Dragging Center moves the orbit in the same screen direction.",
    fixture: "wordmark source with the swirl on",
    id: "swirl.center",
    kind: "control",
    target: engineTargets.swirlCenter,
    timelineCoverage: "keyframes",
    userAction: "Drag the Center pad left, then up.",
  },
  {
    automated: true,
    automatedTestName: "declares the swirl particle count",
    browser: controlBrowser("browser: particles thickens the streams"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Particles adds more characters to the streams.",
    fixture: "wordmark source with the swirl on",
    id: "swirl.count",
    kind: "control",
    target: engineTargets.swirlCount,
    timelineCoverage: "keyframes",
    userAction: "Raise Particles.",
  },
  {
    automated: true,
    automatedTestName: "declares the swirl radius slider",
    browser: controlBrowser("browser: radius widens the orbit"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Radius moves the streams further from the centre.",
    fixture: "wordmark source with the swirl on",
    id: "swirl.radius",
    kind: "control",
    target: engineTargets.swirlRadius,
    timelineCoverage: "keyframes",
    userAction: "Raise Radius.",
  },
  {
    automated: true,
    automatedTestName: "declares the swirl band slider",
    browser: controlBrowser("browser: band spreads the streams"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Band spreads the streams over a wider ring.",
    fixture: "wordmark source with the swirl on",
    id: "swirl.band",
    kind: "control",
    target: engineTargets.swirlBand,
    timelineCoverage: "keyframes",
    userAction: "Raise Band.",
  },
  {
    automated: true,
    automatedTestName: "declares the swirl turns slider",
    browser: controlBrowser("browser: turns sets how fast the streams orbit"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Turns makes the streams circle that many more times per loop.",
    fixture: "wordmark source with the swirl on",
    id: "swirl.turns",
    kind: "control",
    target: engineTargets.swirlTurns,
    timelineCoverage: "keyframes",
    userAction: "Raise Turns and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption switch",
    browser: controlBrowser("browser: the caption sets terminal text over the sheet"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Turning the caption on sets its lines crisply above the sheet and reveals the caption settings; off removes it.",
    fixture: "wordmark source at default settings",
    id: "caption.enabled",
    kind: "control",
    target: engineTargets.captionOn,
    userAction: "Turn Caption text on, then off.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption lines",
    browser: controlBrowser("browser: caption lines are set over the sheet"),
    componentType: "code",
    evidence: "product-output",
    expectedObservable:
      "Each line of text becomes one caption line above the sheet; editing the lines changes what is set.",
    fixture: "wordmark source with a caption",
    id: "caption.text",
    kind: "control",
    target: engineTargets.captionText,
    userAction: "Type two lines of caption text.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption reveal selector",
    browser: controlBrowser("browser: reveal types, decodes or holds the caption"),
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "Type writes the caption on character by character and backspaces it before the loop closes; Decode resolves each character out of scrambled symbols; Static holds it.",
    fixture: "wordmark source with a caption",
    id: "caption.reveal",
    kind: "control",
    optionCoverage: ["type", "decode", "static"],
    target: engineTargets.captionReveal,
    userAction: "Select each option of the Reveal segmented control and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption typography block",
    browser: controlBrowser("browser: every typography part restyles the caption"),
    componentType: "fontPicker",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Font, weight, size, case, colour, opacity, letter spacing and line height each restyle the caption lines.",
    fixture: "wordmark source with a caption",
    id: "caption.type",
    kind: "control",
    target: engineTargets.captionType,
    userAction:
      "Change font, weight, size, case, colour and opacity, letter spacing and line height.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption position vector",
    browser: controlBrowser("browser: position moves the caption block"),
    componentType: "vector",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable: "Dragging Position moves the caption in the same screen direction.",
    fixture: "wordmark source with a caption",
    id: "caption.position",
    kind: "control",
    target: engineTargets.captionPosition,
    timelineCoverage: "keyframes",
    userAction: "Drag the Position pad down, then right.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption highlight text",
    browser: controlBrowser("browser: the highlight word sits in a solid box"),
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Every occurrence of the highlight word is drawn as a solid box with its letters cut out, like selected text.",
    fixture: "wordmark source with a caption",
    id: "caption.highlight",
    kind: "control",
    target: engineTargets.captionHighlight,
    userAction: "Type one word of the caption into Highlight.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption blink switch",
    browser: controlBrowser("browser: blink flashes the highlight and cursor"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "With Blink on the highlight box and cursor flash in time with the loop; off holds them steady.",
    fixture: "wordmark source with a highlighted caption",
    id: "caption.blink",
    kind: "control",
    target: engineTargets.captionBlink,
    userAction: "Toggle Blink and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the caption cursor switch",
    browser: controlBrowser("browser: cursor trails the typed caption"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable: "Turning Cursor on draws an underscore after the last typed character.",
    fixture: "wordmark source with a caption",
    id: "caption.cursor",
    kind: "control",
    target: engineTargets.captionCursor,
    userAction: "Turn Cursor on.",
  },
];
