/** Acceptance rows for the text bars and the logo reveal. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { barTargets } from "../engine/engine-bars";
import { logoTargets } from "../engine/engine-logo";
import { controlBrowser, outputBrowser } from "./acceptance-browser";

const barFixture = "terminal look with Text bars on";
const logoFixture = "terminal look with a logo uploaded and Logo reveal on";
const cinemaFixture = "terminal look with a logo uploaded, Logo reveal on and Cinematic assembly";

type Row = Omit<ToolcraftComponentAcceptance, "automated" | "browser" | "kind"> & {
  browserName: string;
};

const row = ({ browserName, ...rest }: Row): ToolcraftComponentAcceptance =>
  ({ ...rest, automated: true, browser: controlBrowser(browserName), kind: "control" }) as ToolcraftComponentAcceptance;

export const overlayAcceptance: readonly ToolcraftComponentAcceptance[] = [
  row({
    automatedTestName: "declares the text bars switch",
    browserName: "browser: text bars come in, hold and leave",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning Show bars on sends boxed labels through the frame one at a time and reveals their settings; off removes them.",
    fixture: "terminal look at default settings",
    id: "bars.enabled",
    target: barTargets.enabled,
    userAction: "Turn Show bars on and play the loop, then turn it off.",
  }),
  {
    automated: true,
    automatedTestName: "declares the bar list",
    browser: controlBrowser("browser: each bar has its own text and motion"),
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "timeline-output",
    expectedObservable:
      "Each bar in the list is shown in turn with its own text, entrance and departure: from left or right, fired in or out like a bullet with a chevron trail, assembled, decoded or glitched in; slid back, spun away, flipped, shattered, switched off, decoded or glitched out. Adding, editing and removing bars changes which labels appear.",
    fixture: barFixture,
    id: "bars.items",
    kind: "control",
    target: barTargets.items,
    userAction:
      "Add a bar, type its text, pick a different Entrance and Departure for two bars, play the loop, then remove a bar.",
  },
  row({
    automatedTestName: "declares the bars style selector",
    browserName: "browser: style changes the bar's shape",
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Box and Pill set the label cut out of a solid shape; Frame outlines it; Text sets the label alone.",
    fixture: barFixture,
    id: "bars.style",
    optionCoverage: ["box", "capsule", "outline", "text"],
    target: barTargets.style,
    userAction: "Select each option of the Style segmented control.",
  }),
  row({
    automatedTestName: "declares the bars typography block",
    browserName: "browser: every typography part restyles the bars",
    componentType: "fontPicker",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Font, weight, size, case, colour, opacity, letter spacing and line height each restyle the bars; the box takes the text colour.",
    fixture: barFixture,
    id: "bars.type",
    target: barTargets.type,
    userAction: "Change font, weight, size, case, colour and opacity, letter spacing and line height.",
  }),
  row({
    automatedTestName: "declares the bars position vector",
    browserName: "browser: position moves where bars hold",
    componentType: "vector",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable: "Dragging Position moves where the bars hold, in the same screen direction.",
    fixture: barFixture,
    id: "bars.position",
    target: barTargets.position,
    timelineCoverage: "keyframes",
    userAction: "Drag the Position pad up, then left.",
  }),
  row({
    automatedTestName: "declares the bars scatter slider",
    browserName: "browser: scatter spreads the bars out",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Scatter lands successive bars further from Position; 0 stacks them all in one place.",
    fixture: barFixture,
    id: "bars.scatter",
    target: barTargets.scatter,
    timelineCoverage: "keyframes",
    userAction: "Raise Scatter and play the loop.",
  }),
  row({
    automatedTestName: "declares the bar time slider",
    browserName: "browser: bar time paces the bars",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Bar time keeps each bar on screen longer, so fewer bars fit the loop.",
    fixture: barFixture,
    id: "bars.time",
    target: barTargets.time,
    timelineCoverage: "keyframes",
    userAction: "Raise Bar time and play the loop.",
  }),
  row({
    automatedTestName: "declares the bars hold slider",
    browserName: "browser: hold keeps bars still longer",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Hold keeps each bar still for more of its time and makes its entrance and departure quicker.",
    fixture: barFixture,
    id: "bars.hold",
    target: barTargets.hold,
    timelineCoverage: "keyframes",
    userAction: "Raise Hold and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo reveal switch",
    browserName: "browser: the logo assembles from blocks",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning Reveal logo on with a logo uploaded assembles it out of blocks, locks it with a flash and reveals its settings; off removes it.",
    fixture: "terminal look with a logo uploaded",
    id: "logo.enabled",
    target: logoTargets.enabled,
    userAction: "Turn Reveal logo on and play the loop, then turn it off.",
  }),
  {
    automated: true,
    automatedTestName: "declares the logo uploader",
    browser: outputBrowser("browser: an uploaded logo is cut into blocks"),
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable:
      "An uploaded PNG, JPG, WebP or SVG logo is cut into blocks that assemble into it; removing it removes the reveal.",
    fixture: "terminal look with Logo reveal on",
    id: "logo.file",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reset"],
    target: logoTargets.file,
    userAction: "Upload a logo, play the loop, then remove it.",
  },
  row({
    automatedTestName: "declares the logo assembly selector",
    browserName: "browser: assembly changes how the logo builds",
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable:
      "Cinematic flies the pieces in through a moving 3D camera and docks them with impacts; Dot matrix grows it as twinkling dots; Fly in, Build, Scan, Glitch, Sort, Barcode and Swarm each assemble the blocks flat before the logo locks.",
    fixture: logoFixture,
    id: "logo.style",
    optionCoverage: ["cinematic", "dots", "fly", "build", "scan", "glitch", "sort", "barcode", "swarm"],
    target: logoTargets.style,
    userAction: "Select each Assembly and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo departure selector",
    browserName: "browser: departure changes how the logo leaves",
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable:
      "Stay holds the logo to the loop end; Shatter, Reverse, Glitch out and Switch off each take it away after its Hold.",
    fixture: logoFixture,
    id: "logo.exit",
    optionCoverage: ["hold", "shatter", "reverse", "glitch", "collapse"],
    target: logoTargets.exit,
    userAction: "Select each Departure and play past the hold.",
  }),
  row({
    automatedTestName: "declares the logo start selector",
    browserName: "browser: starts chooses when the reveal begins",
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "After starts the reveal once the code roll and end text finish; At start begins it at the top of the loop.",
    fixture: logoFixture,
    id: "logo.timing",
    optionCoverage: ["after", "start"],
    target: logoTargets.timing,
    userAction: "Select each option of the Starts segmented control and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo delay slider",
    browserName: "browser: delay holds the reveal back",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Delay starts the blocks moving later.",
    fixture: logoFixture,
    id: "logo.delay",
    target: logoTargets.delay,
    timelineCoverage: "keyframes",
    userAction: "Raise Delay and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo build time slider",
    browserName: "browser: build time paces the assembly",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Build time slows the assembly and lengthens the timeline to match.",
    fixture: logoFixture,
    id: "logo.build",
    target: logoTargets.build,
    timelineCoverage: "keyframes",
    userAction: "Raise Build time and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo hold slider",
    browserName: "browser: hold keeps the locked logo up",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Hold keeps the finished logo up longer before it leaves.",
    fixture: logoFixture,
    id: "logo.hold",
    target: logoTargets.hold,
    timelineCoverage: "keyframes",
    userAction: "Raise Hold and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo size slider",
    browserName: "browser: size scales the logo",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Raising Size makes the logo wider on the frame, cut into more blocks.",
    fixture: logoFixture,
    id: "logo.size",
    target: logoTargets.size,
    timelineCoverage: "keyframes",
    userAction: "Raise Size.",
  }),
  row({
    automatedTestName: "declares the logo position vector",
    browserName: "browser: position moves the logo",
    componentType: "vector",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable: "Dragging Position moves the logo in the same screen direction.",
    fixture: logoFixture,
    id: "logo.position",
    target: logoTargets.position,
    timelineCoverage: "keyframes",
    userAction: "Drag the Position pad down, then right.",
  }),
  row({
    automatedTestName: "declares the logo block size slider",
    browserName: "browser: block size sets the grain of the build",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Lowering Block size cuts the logo into more, smaller blocks for a finer build.",
    fixture: logoFixture,
    id: "logo.block",
    target: logoTargets.block,
    timelineCoverage: "keyframes",
    userAction: "Lower Block size and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo tint switch",
    browserName: "browser: tint sets the logo in one ink",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable: "With Tint on the logo and its blocks take the Ink; off keeps the logo's own colours.",
    fixture: logoFixture,
    id: "logo.tint",
    target: logoTargets.tint,
    userAction: "Turn Tint off, then on.",
  }),
  row({
    automatedTestName: "declares the logo ink colour",
    browserName: "browser: ink recolours the tinted logo",
    componentType: "color",
    evidence: "product-output",
    expectedObservable: "Changing Ink recolours the tinted logo, its blocks and the HUD.",
    fixture: logoFixture,
    id: "logo.ink",
    target: logoTargets.ink,
    timelineCoverage: "keyframes",
    userAction: "Change Ink.",
  }),
  row({
    automatedTestName: "declares the logo HUD switch",
    browserName: "browser: the HUD frames the build",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "With HUD on, corner brackets open around the logo, with a counter and striped progress bar while it builds and a status line once it locks.",
    fixture: logoFixture,
    id: "logo.hud",
    target: logoTargets.hud,
    userAction: "Turn HUD off, then on, and play the loop.",
  }),
  row({
    automatedTestName: "declares the logo camera selector",
    browserName: "browser: camera changes the cinematic shots",
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable: "Cuts plays three angles with glitch cuts and a whip to the front; Orbit swings round from a steep side; Fly-through rushes in from far away; Front pushes in square on.",
    fixture: cinemaFixture,
    id: "logo.camera",
    optionCoverage: ["cuts", "orbit", "fly", "front"],
    target: logoTargets.camera,
    userAction: "Select each Camera and play the build.",
  }),
  row({
    automatedTestName: "declares the logo angle swing slider",
    browserName: "browser: angle swing turns the camera further",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Angle swing turns the camera further from square on during the build; 0 keeps it frontal.",
    fixture: cinemaFixture,
    id: "logo.swing",
    target: logoTargets.swing,
    timelineCoverage: "keyframes",
    userAction: "Raise Angle swing and play the build.",
  }),
  row({
    automatedTestName: "declares the logo depth slider",
    browserName: "browser: depth extrudes the blocks",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Depth extrudes every block deeper, so angled shots read more solid; 0 leaves flat tiles.",
    fixture: cinemaFixture,
    id: "logo.depth",
    target: logoTargets.depth,
    timelineCoverage: "keyframes",
    userAction: "Raise Depth and play the build.",
  }),
  row({
    automatedTestName: "declares the logo impact slider",
    browserName: "browser: impact strengthens the docking hits",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Impact strengthens each docking flash, shake, shockwave and spark burst and the lock punch.",
    fixture: cinemaFixture,
    id: "logo.impact",
    target: logoTargets.impact,
    timelineCoverage: "keyframes",
    userAction: "Raise Impact and play the build.",
  }),
  row({
    automatedTestName: "declares the logo pieces slider",
    browserName: "browser: pieces cuts the logo into more parts",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Pieces cuts the logo into more parts that each fly in and dock on their own.",
    fixture: cinemaFixture,
    id: "logo.parts",
    target: logoTargets.parts,
    timelineCoverage: "keyframes",
    userAction: "Raise Pieces and play the build.",
  }),
  row({
    automatedTestName: "declares the logo particle selector",
    browserName: "browser: particles changes what the logo is built from",
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable: "Blocks, Dots, Dashes, Glyphs, Plus and Boxed build the logo from that particle; Morph turns each cell from dash to dot to box to block as it lands.",
    fixture: cinemaFixture,
    id: "logo.particle",
    optionCoverage: ["blocks", "dots", "dashes", "glyphs", "plus", "boxed", "mixed"],
    target: logoTargets.particle,
    userAction: "Select each Particles option and play the build.",
  }),
  row({
    automatedTestName: "declares the logo floor grid switch",
    browserName: "browser: floor grid turns with the camera",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable: "With Floor grid on, a perspective grid floor turns with the camera during the build; off removes it.",
    fixture: cinemaFixture,
    id: "logo.floor",
    target: logoTargets.floor,
    userAction: "Turn Floor grid off, then on, and play the build.",
  }),
  row({
    automatedTestName: "declares the logo debris switch",
    browserName: "browser: debris rushes past the camera",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable: "With Debris on, debris cubes and speed streaks rush past the camera during the build; off removes them.",
    fixture: cinemaFixture,
    id: "logo.streaks",
    target: logoTargets.streaks,
    userAction: "Turn Debris off, then on, and play the build.",
  }),
];
