/** Acceptance rows for the sampling stages: background, source, grid, unit and tone. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { engineTargets } from "../engine/engine-settings";
import { controlBrowser, outputBrowser, renderBrowser } from "./acceptance-browser";

export const samplingAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "declares the Background switch that controls export alpha",
    backgroundOutputCoverage: "all-required-background-output",
    browser: renderBrowser(
      "browser: background switch fills the sheet and clears PNG alpha",
    ),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Turning Background off leaves the halftone sheet transparent in preview and in the exported PNG.",
    fixture: "wordmark source at default settings",
    id: "background.include",
    kind: "control",
    target: engineTargets.includeBackground,
    userAction: "Toggle Background in Settings and export a PNG.",
  },
  {
    automated: true,
    automatedTestName: "declares the product background color control",
    browser: renderBrowser("browser: background color repaints the sheet"),
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable:
      "The field behind the units takes the selected colour in preview and export.",
    fixture: "wordmark source at default settings",
    id: "background.color",
    kind: "control",
    target: engineTargets.background,
    timelineCoverage: "keyframes",
    userAction: "Change Background color in Settings.",
  },
  {
    automated: true,
    automatedTestName: "declares the canonical source kind selector",
    browser: controlBrowser(
      "browser: source kind swaps the visible source control and the sampled grid",
    ),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Image, SVG and Video each show only their own uploader; Text shows the wordmark field and typeface block and renders units without any upload.",
    fixture: "wordmark source plus one uploaded image",
    id: "source.kind",
    kind: "control",
    optionCoverage: ["image", "svg", "video", "text"],
    target: engineTargets.sourceKind,
    userAction: "Select each option of the Source segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the raster source uploader",
    browser: outputBrowser("browser: uploading an image halftones its tone"),
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable:
      "An uploaded image appears in the control and its luminance becomes the unit grid; removing it clears the sheet and Reset restores the empty source.",
    fixture: "one uploaded source image in Image mode",
    id: "source.image",
    kind: "control",
    mediaLifecycleCoverage: [
      "upload",
      "remove",
      "reset",
      "rotate",
      "flip",
      "transform-output",
    ],
    target: engineTargets.sourceImage,
    userAction: "Upload an image, remove it, then reset the section.",
  },
  {
    automated: true,
    automatedTestName: "declares the vector source uploader",
    browser: outputBrowser("browser: uploading an SVG halftones its silhouette"),
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable:
      "An uploaded SVG rasterizes into the unit grid and removing it clears the sheet.",
    fixture: "one uploaded SVG in SVG mode",
    id: "source.svg",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reset"],
    target: engineTargets.sourceSvg,
    userAction: "Upload an SVG in SVG mode, then remove it.",
  },
  {
    automated: true,
    automatedTestName: "declares the footage source uploader",
    browser: outputBrowser(
      "browser: uploaded footage halftones the frame at the playhead",
    ),
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable:
      "Uploaded footage decodes one frame per timeline time, so scrubbing changes the sampled grid; removing it clears the sheet.",
    fixture: "one uploaded video in Video mode",
    id: "source.video",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reset"],
    target: engineTargets.sourceVideo,
    userAction: "Upload footage in Video mode, scrub the timeline, then remove it.",
  },
  {
    automated: true,
    automatedTestName: "declares the wordmark text control",
    browser: controlBrowser("browser: wordmark text changes the halftoned letters"),
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Typing a different wordmark re-rasterizes the mask and the drawn units spell the new text.",
    fixture: "wordmark source at default settings",
    id: "source.text",
    kind: "control",
    target: engineTargets.sourceText,
    userAction: "Type a different wordmark in Text mode.",
  },
  {
    automated: true,
    automatedTestName: "declares the wordmark typography block",
    browser: controlBrowser(
      "browser: every typography part changes the halftoned wordmark",
    ),
    componentType: "fontPicker",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Font, weight, size, case, colour, opacity, letter spacing and line height each change the rasterized mask, so the unit field changes with them.",
    fixture: "wordmark source at default settings",
    id: "source.type",
    kind: "control",
    target: engineTargets.sourceType,
    userAction:
      "Change font, weight, size, case, colour and opacity, letter spacing and line height.",
  },
  {
    automated: true,
    automatedTestName: "declares the cell size workload slider",
    browser: controlBrowser("browser: cell size changes the drawn unit count"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "A smaller cell size produces a denser grid with more, smaller units; a larger one produces fewer, larger units.",
    fixture: "wordmark source at default settings",
    id: "grid.cell",
    kind: "control",
    target: engineTargets.cell,
    timelineCoverage: "keyframes",
    userAction: "Drag Cell size from its default toward its minimum.",
  },
  {
    automated: true,
    automatedTestName: "declares the cell gap slider",
    browser: controlBrowser("browser: gap shrinks each unit inside its cell"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Gap leaves the grid pitch unchanged while each unit occupies less of its cell.",
    fixture: "wordmark source at default settings",
    id: "grid.gap",
    kind: "control",
    target: engineTargets.gap,
    timelineCoverage: "keyframes",
    userAction: "Raise Gap from zero.",
  },
  {
    automated: true,
    automatedTestName: "declares the cell jitter slider",
    browser: controlBrowser("browser: jitter offsets units off the grid"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Jitter displaces each unit from its cell centre by a stable per-cell amount.",
    fixture: "wordmark source at default settings",
    id: "grid.jitter",
    kind: "control",
    target: engineTargets.jitter,
    timelineCoverage: "keyframes",
    userAction: "Raise Jitter from zero.",
  },
  {
    automated: true,
    automatedTestName: "declares the grid layout selector",
    browser: controlBrowser("browser: columns layout stretches units vertically"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Square keeps units isotropic; Columns lets ink drive vertical length so the sheet reads as scanline bars.",
    fixture: "wordmark source at default settings",
    id: "grid.mode",
    kind: "control",
    optionCoverage: ["square", "columns"],
    target: engineTargets.layout,
    userAction: "Select each option of the Layout segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the unit rotation slider",
    browser: controlBrowser("browser: rotation turns every unit"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Each drawn unit rotates by the selected angle.",
    fixture: "wordmark source with square units",
    id: "unit.angle",
    kind: "control",
    target: engineTargets.unitAngle,
    timelineCoverage: "keyframes",
    userAction: "Move Rotation away from zero with a square unit selected.",
  },
  {
    automated: true,
    automatedTestName: "declares the unit floor slider",
    browser: controlBrowser("browser: floor gives faint cells a visible unit"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Floor lifts the smallest units so low-ink cells still draw a mark.",
    fixture: "wordmark source at default settings",
    id: "unit.floor",
    kind: "control",
    target: engineTargets.unitFloor,
    timelineCoverage: "keyframes",
    userAction: "Raise Floor from zero.",
  },
  {
    automated: true,
    automatedTestName: "declares the editable glyph set",
    browser: controlBrowser(
      "browser: adding and editing glyphs changes the drawn marks",
    ),
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "product-output",
    expectedObservable:
      "Each entry is drawn as the repeated unit; adding, editing and removing entries changes which symbols appear on the sheet.",
    fixture: "wordmark source with the glyph unit selected",
    id: "unit.glyphs",
    kind: "control",
    target: engineTargets.glyphs,
    userAction: "Add a glyph, edit an entry, then remove the last entry.",
  },
  {
    automated: true,
    automatedTestName: "declares the glyph tone ramp switch",
    browser: controlBrowser("browser: tone ramp maps ink to glyph density"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "On selects a glyph by ink level so dense symbols land in dark areas; off cycles glyphs by position instead.",
    fixture: "wordmark source with the glyph unit selected",
    id: "unit.ramp",
    kind: "control",
    target: engineTargets.ramp,
    userAction: "Toggle Tone ramp with the glyph unit selected.",
  },
  {
    automated: true,
    automatedTestName: "declares the tone response slider",
    browser: controlBrowser("browser: tone response scales unit size with ink"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Tone response makes units grow faster with ink; zero holds every unit at the floor size.",
    fixture: "wordmark source at default settings",
    id: "unit.scale",
    kind: "control",
    target: engineTargets.scale,
    timelineCoverage: "keyframes",
    userAction: "Move Tone response away from its default.",
  },
  {
    automated: true,
    automatedTestName: "declares the unit shape selector",
    browser: controlBrowser("browser: every unit shape draws its own mark"),
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Circle, Square, Octagon, Ring, Bar and Glyph each draw a distinct mark, and Glyph reveals the glyph set and tone ramp.",
    fixture: "wordmark source at default settings",
    id: "unit.shape",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: engineTargets.shape,
    userAction: "Select each option of the Shape select.",
  },
  {
    automated: true,
    automatedTestName: "declares the tone contrast slider",
    browser: controlBrowser("browser: contrast redistributes ink across the grid"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Contrast pushes cells toward full or empty ink; lowering it flattens the field.",
    fixture: "wordmark source at default settings",
    id: "tone.contrast",
    kind: "control",
    target: engineTargets.contrast,
    timelineCoverage: "keyframes",
    userAction: "Move Contrast away from zero.",
  },
  {
    automated: true,
    automatedTestName: "declares the threshold cutoff slider",
    browser: controlBrowser("browser: cutoff moves the threshold edge"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "With Threshold dither selected, Cutoff decides which cells keep ink and which clear.",
    fixture: "wordmark source with threshold dither selected",
    id: "tone.cutoff",
    kind: "control",
    target: engineTargets.cutoff,
    timelineCoverage: "keyframes",
    userAction: "Select Threshold dither and move Cutoff.",
  },
  {
    automated: true,
    automatedTestName: "declares the dither engine selector",
    browser: controlBrowser(
      "browser: every dither engine redistributes ink differently",
    ),
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "None keeps continuous ink, Threshold reveals Cutoff and clips hard, and the Bayer, Floyd-Steinberg and blue-noise engines each produce their own distribution.",
    fixture: "wordmark source at default settings",
    id: "tone.dither",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: engineTargets.dither,
    userAction: "Select each option of the Dither select.",
  },
  {
    automated: true,
    automatedTestName: "declares the tone invert switch",
    browser: controlBrowser("browser: invert swaps inked and empty cells"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Invert exchanges the inked and empty regions of the sheet.",
    fixture: "wordmark source at default settings",
    id: "tone.invert",
    kind: "control",
    target: engineTargets.invert,
    userAction: "Toggle Invert.",
  },
  {
    automated: true,
    automatedTestName: "declares the tone lightness slider",
    browser: controlBrowser("browser: lightness shifts overall ink"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Lightness adds ink across every cell; lowering it removes ink.",
    fixture: "wordmark source at default settings",
    id: "tone.lightness",
    kind: "control",
    target: engineTargets.lightness,
    timelineCoverage: "keyframes",
    userAction: "Move Lightness away from zero.",
  },
  {
    automated: true,
    automatedTestName: "declares the tone response curve",
    browser: controlBrowser("browser: the response curve remaps sampled ink"),
    componentType: "curves",
    controlPartCoverage: ["curves.points"],
    evidence: "product-output",
    expectedObservable:
      "Dragging a point off the diagonal remaps sampled ink, changing unit sizes across the sheet.",
    fixture: "wordmark source at default settings",
    id: "tone.response",
    kind: "control",
    target: engineTargets.response,
    timelineCoverage: "keyframes",
    userAction: "Drag an off-centre point on the Response curve.",
  },
];
