/** Acceptance rows for the data text and the glitch fillers between scenes. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { dataTextTargets } from "../engine/engine-datatext";
import { transitionTargets } from "../engine/engine-transition";
import { controlBrowser } from "./acceptance-browser";

const dataFixture = "terminal look with Data text on";
const fillerFixture = "code roll, end text and logo on with Glitch filler on";

type Row = Omit<ToolcraftComponentAcceptance, "automated" | "browser" | "kind"> & {
  browserName: string;
};

const row = ({ browserName, ...rest }: Row): ToolcraftComponentAcceptance =>
  ({ ...rest, automated: true, browser: controlBrowser(browserName), kind: "control" }) as ToolcraftComponentAcceptance;

export const sequenceAcceptance: readonly ToolcraftComponentAcceptance[] = [
  row({
    automatedTestName: "declares the data text switch",
    browserName: "browser: data text decodes on at different places",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning Show data text on decodes small labels on one after another at different places, with markers, stepped rules, a wordmark and a boxed tag, and reveals its settings; off removes them.",
    fixture: "terminal look at default settings",
    id: "data.enabled",
    target: dataTextTargets.enabled,
    userAction: "Turn Show data text on and play the loop, then turn it off.",
  }),
  row({
    automatedTestName: "declares the data item list",
    browserName: "browser: each item has its own text, style, place, size and delay",
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "timeline-output",
    expectedObservable:
      "Each item is drawn with its own text, style, position, size and delay: labels, bullet labels, a wide wordmark or a boxed tag. Adding, editing and removing items changes which labels appear and where.",
    fixture: dataFixture,
    id: "data.items",
    target: dataTextTargets.items,
    userAction: "Add an item, type its text, move it and change its style and size, play the loop, then remove an item.",
  }),
  row({
    automatedTestName: "declares the data text typography block",
    browserName: "browser: every typography part restyles the data text",
    componentType: "fontPicker",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Font, weight, size, case, colour, opacity, letter spacing and line height each restyle every item; size scales them together.",
    fixture: dataFixture,
    id: "data.type",
    target: dataTextTargets.type,
    userAction: "Change font, weight, size, case, colour and opacity, letter spacing and line height.",
  }),
  row({
    automatedTestName: "declares the data reveal selector",
    browserName: "browser: reveal changes how items come on",
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable: "Decode resolves characters out of noise, Type runs a caret, Flicker stutters each item on.",
    fixture: dataFixture,
    id: "data.reveal",
    optionCoverage: ["decode", "type", "flicker"],
    target: dataTextTargets.reveal,
    userAction: "Select each option of the Reveal segmented control and play the loop.",
  }),
  row({
    automatedTestName: "declares the data departure selector",
    browserName: "browser: departure changes how items leave",
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "Decode clears each item through noise, Bullet backspaces it into a blinking square, Cut drops everything at once, Stay keeps it to the loop end.",
    fixture: dataFixture,
    id: "data.exit",
    optionCoverage: ["decode", "bullet", "cut", "stay"],
    target: dataTextTargets.exit,
    userAction: "Select each option of the Departure segmented control and play past the hold.",
  }),
  row({
    automatedTestName: "declares the data start selector",
    browserName: "browser: starts chooses when the data text begins",
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable: "After starts the first item once the code roll, end text and logo finish; With logo starts it with the logo; At start begins at the top of the loop.",
    fixture: dataFixture,
    id: "data.timing",
    optionCoverage: ["after", "logo", "start"],
    target: dataTextTargets.timing,
    userAction: "Select each option of the Starts segmented control and play the loop.",
  }),
  row({
    automatedTestName: "declares the data start delay slider",
    browserName: "browser: start delay holds the data text back",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Start delay makes the first item appear later.",
    fixture: dataFixture,
    id: "data.start",
    target: dataTextTargets.start,
    timelineCoverage: "keyframes",
    userAction: "Raise Start delay and play the loop.",
  }),
  row({
    automatedTestName: "declares the data stagger slider",
    browserName: "browser: stagger spaces the items out",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Stagger leaves more time between one item starting and the next; 0 starts them together.",
    fixture: dataFixture,
    id: "data.stagger",
    target: dataTextTargets.stagger,
    timelineCoverage: "keyframes",
    userAction: "Raise Stagger and play the loop.",
  }),
  row({
    automatedTestName: "declares the data hold slider",
    browserName: "browser: hold keeps items up longer",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Hold keeps each revealed item on screen longer before it leaves.",
    fixture: dataFixture,
    id: "data.hold",
    target: dataTextTargets.hold,
    timelineCoverage: "keyframes",
    userAction: "Raise Hold and play the loop.",
  }),
  row({
    automatedTestName: "declares the data tile switch",
    browserName: "browser: tile block repeats the labels up and down",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable: "With Tile block on, whole copies of the label block repeat up and down the frame.",
    fixture: dataFixture,
    id: "data.repeat",
    target: dataTextTargets.repeat,
    userAction: "Turn Tile block on, then off.",
  }),
  row({
    automatedTestName: "declares the data box colour",
    browserName: "browser: box recolours boxed items",
    componentType: "color",
    evidence: "product-output",
    expectedObservable: "Changing Box recolours the fill of Boxed items, and their text turns dark or light to suit.",
    fixture: dataFixture,
    id: "data.box",
    target: dataTextTargets.box,
    timelineCoverage: "keyframes",
    userAction: "Change Box.",
  }),
  row({
    automatedTestName: "declares the data markers switch",
    browserName: "browser: markers dot the grid",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable: "With Markers on, square markers in pairs and singles dot the column grid at the top and bottom; off removes them.",
    fixture: dataFixture,
    id: "data.markers",
    target: dataTextTargets.markers,
    userAction: "Turn Markers off, then on.",
  }),
  row({
    automatedTestName: "declares the data rules switch",
    browserName: "browser: rules grow into stepped bars",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable: "With Rules on, thin rules grow out of a square and thicken into stepped bars above and below the block; off removes them.",
    fixture: dataFixture,
    id: "data.rules",
    target: dataTextTargets.rules,
    userAction: "Turn Rules off, then on, and play the loop.",
  }),
  row({
    automatedTestName: "declares the glitch filler switch",
    browserName: "browser: a glitch filler hides each cut",
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning Glitch filler on covers each cut and the loop seam with a short glitch filler and reveals its settings; off cuts straight from scene to scene.",
    fixture: "code roll, end text and logo on",
    id: "transition.enabled",
    target: transitionTargets.enabled,
    userAction: "Turn Glitch filler on and play the loop, then turn it off.",
  }),
  row({
    automatedTestName: "declares the filler style selector",
    browserName: "browser: style changes the filler",
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable:
      "Glow sweeps a stepped dome of hot pixels in a soft bloom; Mosaic breaks the frame into cooling pixels; Slice tears it with dark slabs; Scan shuts it off line by line; Grid wipe closes a halftone of squares.",
    fixture: fillerFixture,
    id: "transition.style",
    optionCoverage: ["glow", "mosaic", "slice", "scan", "grid"],
    target: transitionTargets.style,
    userAction: "Select each Style and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler placement selector",
    browserName: "browser: placement chooses where fillers play",
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "Cuts plays fillers between scenes, Seam across the loop's end and start, Both does both, and Beats fires them on strong beats of the song and reveals Beat threshold.",
    fixture: fillerFixture,
    id: "transition.placement",
    optionCoverage: ["cuts", "loop", "both", "beats"],
    target: transitionTargets.placement,
    userAction: "Select each option of the Placement segmented control and play the loop.",
  }),
  row({
    automatedTestName: "declares the filler beat threshold slider",
    browserName: "browser: beat threshold picks which beats fire",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Beat threshold fires fillers on fewer, stronger beats.",
    fixture: "terminal look with a song, Audio reactive and Glitch filler on Beats",
    id: "transition.threshold",
    target: transitionTargets.threshold,
    timelineCoverage: "keyframes",
    userAction: "Raise Beat threshold and play the loop.",
  }),
  row({
    automatedTestName: "declares the filler direction selector",
    browserName: "browser: direction turns the filler",
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable: "Up, Down, Left and Right send the filler across the frame that way.",
    fixture: fillerFixture,
    id: "transition.direction",
    optionCoverage: ["up", "down", "left", "right"],
    target: transitionTargets.direction,
    userAction: "Select each option of the Direction segmented control and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler duration slider",
    browserName: "browser: duration lengthens the filler",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Duration keeps each filler on screen longer.",
    fixture: fillerFixture,
    id: "transition.duration",
    target: transitionTargets.duration,
    timelineCoverage: "keyframes",
    userAction: "Raise Duration and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler hold slider",
    browserName: "browser: hold keeps the frame covered longer",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Hold keeps the frame fully covered for more of each filler.",
    fixture: fillerFixture,
    id: "transition.hold",
    target: transitionTargets.hold,
    timelineCoverage: "keyframes",
    userAction: "Raise Hold and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler intensity slider",
    browserName: "browser: intensity brightens the filler",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Intensity strengthens the bloom, hot pixels, glints, grain and tearing.",
    fixture: fillerFixture,
    id: "transition.intensity",
    target: transitionTargets.intensity,
    timelineCoverage: "keyframes",
    userAction: "Raise Intensity and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler blocks slider",
    browserName: "browser: blocks sets the filler's pixel size",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Lowering Blocks makes the filler's pixels bigger and chunkier; raising it makes them finer.",
    fixture: fillerFixture,
    id: "transition.blocks",
    target: transitionTargets.blocks,
    timelineCoverage: "keyframes",
    userAction: "Lower Blocks and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler glow colour",
    browserName: "browser: glow colour tints the light",
    componentType: "color",
    evidence: "timeline-output",
    expectedObservable: "Changing Glow color tints the filler's light; its white-hot core follows.",
    fixture: fillerFixture,
    id: "transition.color",
    target: transitionTargets.color,
    timelineCoverage: "keyframes",
    userAction: "Change Glow color and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler cover colour",
    browserName: "browser: cover colour sets the dark",
    componentType: "color",
    evidence: "timeline-output",
    expectedObservable: "Changing Cover color changes the dark the filler holds while the shot changes.",
    fixture: fillerFixture,
    id: "transition.fill",
    target: transitionTargets.fill,
    timelineCoverage: "keyframes",
    userAction: "Change Cover color and play across a cut.",
  }),
  row({
    automatedTestName: "declares the filler cover slider",
    browserName: "browser: cover lets the shot show through",
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Lowering Cover opacity lets the shot show through the filler's dark; 0 leaves only the light.",
    fixture: fillerFixture,
    id: "transition.cover",
    target: transitionTargets.cover,
    timelineCoverage: "keyframes",
    userAction: "Lower Cover opacity and play across a cut.",
  }),
];
