/** Acceptance rows for the code roll and the end text that follows it. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { engineTargets } from "../engine/engine-settings";
import { controlBrowser } from "./acceptance-browser";

const rollFixture = "code roll on at default settings";
const endFixture = "code roll and end text on at default settings";

export const codeAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "declares the code roll switch",
    browser: controlBrowser("browser: the code roll takes over the canvas"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning Roll code on replaces the sheet with the code text, which rolls in and then breaks apart into swirling characters; off returns the sheet.",
    fixture: "wordmark source at default settings",
    id: "code.enabled",
    kind: "control",
    target: engineTargets.codeOn,
    userAction: "Turn Roll code on and play the loop, then turn it off.",
  },
  {
    automated: true,
    automatedTestName: "declares the code text",
    browser: controlBrowser("browser: each line of code becomes a terminal line"),
    componentType: "code",
    evidence: "product-output",
    expectedObservable:
      "Each line becomes one terminal line, and the part after a tab sits flush against the right edge.",
    fixture: rollFixture,
    id: "code.text",
    kind: "control",
    target: engineTargets.codeText,
    userAction: "Replace the code with three lines, one with a tab before a status tag.",
  },
  {
    automated: true,
    automatedTestName: "declares the code scroll selector",
    browser: controlBrowser("browser: scroll fills, rolls up or rolls down"),
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "Terminal adds lines from the top and scrolls once the screen is full; Roll up brings the block in from the bottom; Roll down brings it in from the top.",
    fixture: rollFixture,
    id: "code.motion",
    kind: "control",
    optionCoverage: ["terminal", "up", "down"],
    target: engineTargets.codeMotion,
    userAction: "Select each option of the Scroll segmented control and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the code typography block",
    browser: controlBrowser("browser: every typography part restyles the code"),
    componentType: "fontPicker",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Font, weight, size, case, colour, opacity, letter spacing and line height each restyle the code lines.",
    fixture: rollFixture,
    id: "code.type",
    kind: "control",
    target: engineTargets.codeType,
    userAction:
      "Change font, weight, size, case, colour and opacity, letter spacing and line height.",
  },
  {
    automated: true,
    automatedTestName: "declares the code roll time slider",
    browser: controlBrowser("browser: roll time paces the text"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "Raising Roll time makes the text take longer to arrive; lowering it brings the text in faster.",
    fixture: rollFixture,
    id: "code.rollTime",
    kind: "control",
    target: engineTargets.codeRollTime,
    timelineCoverage: "keyframes",
    userAction: "Raise Roll time and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the code reveal selector",
    browser: controlBrowser("browser: reveal changes how each line arrives"),
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "Line sets each line whole; Type writes it on behind a block cursor; Decode resolves it out of scrambled symbols; Glitch lands it doubled and flickering before it settles.",
    fixture: rollFixture,
    id: "code.reveal",
    kind: "control",
    optionCoverage: ["line", "type", "decode", "glitch"],
    target: engineTargets.codeReveal,
    userAction: "Select each option of the Reveal segmented control and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the code hold slider",
    browser: controlBrowser("browser: hold keeps the text still before the break"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "Raising Hold time keeps the arrived text still for longer before it breaks apart, and lengthens the timeline by the same amount.",
    fixture: rollFixture,
    id: "code.hold",
    kind: "control",
    target: engineTargets.codeHold,
    timelineCoverage: "keyframes",
    userAction: "Raise Hold time and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the code break style selector",
    browser: controlBrowser("browser: break style changes how the text comes apart"),
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable:
      "Swirl streams the characters away in ribbons; Burst blasts them out from the centre; Vortex drains them into the middle; Fall drops them; Wind sweeps them off to the right; Glitch scrambles them and flickers them out.",
    fixture: rollFixture,
    id: "code.breakStyle",
    kind: "control",
    optionCoverage: ["swirl", "burst", "vortex", "fall", "wind", "glitch"],
    target: engineTargets.codeBreakStyle,
    userAction: "Select each Break style and play past the hold.",
  },
  {
    automated: true,
    automatedTestName: "declares the code break time slider",
    browser: controlBrowser("browser: break time stretches the break"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "Raising Break time spreads the breaking characters over longer, so they swirl further before they fade.",
    fixture: rollFixture,
    id: "code.breakTime",
    kind: "control",
    target: engineTargets.codeBreakTime,
    timelineCoverage: "keyframes",
    userAction: "Raise Break time and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the sheet at end switch",
    browser: controlBrowser("browser: sheet at end brings the sheet back"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "With Sheet at end on, the halftone sheet returns once the code has broken away; off keeps the canvas clear.",
    fixture: rollFixture,
    id: "code.sheetAtEnd",
    kind: "control",
    target: engineTargets.codeSheetAtEnd,
    userAction: "Turn Sheet at end on and play past the break.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text switch",
    browser: controlBrowser("browser: end text follows the code roll"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "Turning Show end text on types the end text on once the code has broken away and reveals its settings; off removes it.",
    fixture: rollFixture,
    id: "endText.enabled",
    kind: "control",
    target: engineTargets.endOn,
    userAction: "Turn Show end text on and play the loop, then turn it off.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text lines",
    browser: controlBrowser("browser: end text lines are set after the roll"),
    componentType: "code",
    evidence: "product-output",
    expectedObservable: "Each line of text becomes one end text line; editing the lines changes what is set.",
    fixture: endFixture,
    id: "endText.text",
    kind: "control",
    target: engineTargets.endText,
    userAction: "Type two lines of end text.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text reveal selector",
    browser: controlBrowser("browser: reveal types, decodes or holds the end text"),
    componentType: "segmented",
    evidence: "timeline-output",
    expectedObservable:
      "Type writes the end text on character by character and backspaces it as its hold ends; Decode resolves each character out of scrambled symbols; Static holds it.",
    fixture: endFixture,
    id: "endText.reveal",
    kind: "control",
    optionCoverage: ["type", "decode", "static"],
    target: engineTargets.endReveal,
    userAction: "Select each option of the Reveal segmented control and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text hold slider",
    browser: controlBrowser("browser: hold keeps the end text up longer"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable: "Raising Hold keeps the end text up for longer before it clears.",
    fixture: endFixture,
    id: "endText.hold",
    kind: "control",
    target: engineTargets.endHold,
    timelineCoverage: "keyframes",
    userAction: "Raise Hold and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text typography block",
    browser: controlBrowser("browser: every typography part restyles the end text"),
    componentType: "fontPicker",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable:
      "Font, weight, size, case, colour, opacity, letter spacing and line height each restyle the end text.",
    fixture: endFixture,
    id: "endText.type",
    kind: "control",
    target: engineTargets.endType,
    userAction:
      "Change font, weight, size, case, colour and opacity, letter spacing and line height.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text position vector",
    browser: controlBrowser("browser: position moves the end text block"),
    componentType: "vector",
    controlPartCoverage: "all-visible-parts",
    evidence: "product-output",
    expectedObservable: "Dragging Position moves the end text in the same screen direction.",
    fixture: endFixture,
    id: "endText.position",
    kind: "control",
    target: engineTargets.endPosition,
    timelineCoverage: "keyframes",
    userAction: "Drag the Position pad down, then right.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text highlight text",
    browser: controlBrowser("browser: the end text highlight word sits in a solid box"),
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Every occurrence of the highlight word is drawn as a solid box with its letters cut out, like selected text.",
    fixture: endFixture,
    id: "endText.highlight",
    kind: "control",
    target: engineTargets.endHighlight,
    userAction: "Type one word of the end text into Highlight.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text blink switch",
    browser: controlBrowser("browser: blink flashes the end text highlight and cursor"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable:
      "With Blink on the highlight box and cursor flash while the end text is up; off holds them steady.",
    fixture: "code roll and end text on with a highlight word",
    id: "endText.blink",
    kind: "control",
    target: engineTargets.endBlink,
    userAction: "Toggle Blink and play the loop.",
  },
  {
    automated: true,
    automatedTestName: "declares the end text cursor switch",
    browser: controlBrowser("browser: cursor trails the typed end text"),
    componentType: "switch",
    evidence: "timeline-output",
    expectedObservable: "Turning Cursor on draws an underscore after the last typed character.",
    fixture: endFixture,
    id: "endText.cursor",
    kind: "control",
    target: engineTargets.endCursor,
    userAction: "Turn Cursor on.",
  },
];
