/** Acceptance rows for colour, guides and mark mixing: palette, guides, mix and match. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { engineTargets } from "../engine/engine-settings";
import { controlBrowser, renderBrowser } from "./acceptance-browser";

export const editingAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "declares the editable brand ink list",
    browser: controlBrowser("browser: ink entries colour the tone bands"),
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "product-output",
    expectedObservable:
      "Ink is quantized across the entries in order, so editing, adding or removing an ink changes the colours drawn on the sheet.",
    fixture: "wordmark source at default settings",
    id: "palette.inks",
    kind: "control",
    target: engineTargets.inks,
    userAction: "Edit an ink, add one, then remove the last entry.",
  },
  {
    automated: true,
    automatedTestName: "declares the palette mode selector",
    browser: controlBrowser("browser: palette mode switches ink source"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Inks quantizes to the brand list and shows it; Source keeps each sampled pixel colour and hides the list.",
    fixture: "one uploaded colour image",
    id: "palette.mode",
    kind: "control",
    optionCoverage: ["full", "inks", "source"],
    target: engineTargets.paletteMode,
    userAction: "Select each option of the Color segmented control.",
  },
  {
    actionCoverage: ["palette.shuffle"],
    automated: true,
    automatedTestName: "declares the ink shuffle command",
    browser: controlBrowser(
      "browser: shuffle reorders the ink list and the sheet",
    ),
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable:
      "Shuffle reorders the ink entries, so the tone bands take different colours.",
    fixture: "wordmark source with three inks",
    id: "palette.shuffle",
    kind: "control",
    target: "palette.shuffle",
    userAction: "Press Shuffle with three or more inks.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion amount slider",
    browser: controlBrowser("browser: motion amount scales the animated offset"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "With a motion style selected, Amount scales how far each unit departs from its still size.",
    fixture: "wordmark source with pulse motion",
    id: "motion.amount",
    kind: "control",
    target: engineTargets.motionAmount,
    timelineCoverage: "keyframes",
    userAction: "Select a motion style and move Amount.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion stagger slider",
    browser: controlBrowser("browser: stagger delays units across the grid"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "Raising Stagger delays each unit by its distance from the top-left corner, so the cycle travels across the sheet.",
    fixture: "wordmark source with pulse motion",
    id: "motion.stagger",
    kind: "control",
    target: engineTargets.motionStagger,
    timelineCoverage: "keyframes",
    userAction: "Select a motion style and move Stagger.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion style selector",
    browser: controlBrowser("browser: every motion style animates its own way"),
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable:
      "Still leaves the sheet fixed and hides the motion settings; each of the twenty-one animated styles moves the units its own way, and the travelling styles also reveal Direction.",
    fixture: "wordmark source at default settings",
    id: "motion.style",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: engineTargets.motionStyle,
    userAction: "Select each option of the Motion select.",
  },
  {
    automated: true,
    automatedTestName: "declares the cell grid guide",
    browser: renderBrowser("browser: cell grid draws guides that stay out of exports"),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "The grid guide appears over the sheet in preview and is absent from an exported still.",
    fixture: "wordmark source at default settings",
    id: "view.grid",
    kind: "control",
    target: engineTargets.gridOverlay,
    userAction: "Turn Cell grid on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares the circle guide",
    browser: renderBrowser("browser: circle guide draws a guide that stays out of exports"),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "The circular guide appears over the sheet in preview and is absent from an exported still.",
    fixture: "wordmark source at default settings",
    id: "view.circle",
    kind: "control",
    target: engineTargets.circleOverlay,
    userAction: "Turn Circle guide on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares the greyscale palette switch",
    browser: controlBrowser("browser: greyscale converts every drawn ink to luma"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Every unit, backdrop and effect mark is drawn at its perceptual luma instead of its colour.",
    fixture: "wordmark source at default settings",
    id: "palette.greyscale",
    kind: "control",
    target: engineTargets.greyscale,
    userAction: "Turn Greyscale on.",
  },
  {
    automated: true,
    automatedTestName: "declares the flat ink export switch",
    browser: renderBrowser("browser: flat ink draws every unit in one colour"),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Every unit is drawn in the first ink instead of its own colour, in preview and in the exported still.",
    fixture: "wordmark source with a multi-ink palette",
    id: "output.flat-ink",
    kind: "control",
    target: engineTargets.ignoreColor,
    userAction: "Turn Flat ink on export on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares the editable mark mix",
    browser: controlBrowser("browser: a mix draws every chosen mark on one sheet"),
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "product-output",
    expectedObservable:
      "With Shape set to Mix, every entry appears somewhere on the sheet, so a square and a glyph are drawn together; repeating an entry makes it more common.",
    fixture: "one uploaded source image with Shape set to Mix",
    id: "unit.mix",
    kind: "control",
    target: engineTargets.mix,
    userAction: "Set Shape to Mix, add a Glyph entry beside Square, then remove the last entry.",
  },
  {
    automated: true,
    automatedTestName: "declares the mix spread selector",
    browser: controlBrowser("browser: spread changes how the mix is distributed"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Random scatters the marks, Cycle alternates them in reading order, and Tone assigns them by cell brightness.",
    fixture: "one uploaded source image with Shape set to Mix",
    id: "unit.mix-order",
    kind: "control",
    optionCoverage: ["random", "cycle", "tone"],
    target: engineTargets.mixDistribution,
    userAction: "Select each option of the Spread segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the colour match selector",
    browser: controlBrowser("browser: colour match changes how inks are assigned"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Tone bands the sheet by brightness, Nearest gives each cell its closest ink so separate hues stay separate, and Blend weights the two closest inks.",
    fixture: "one uploaded colour image with several inks",
    id: "palette.match",
    kind: "control",
    optionCoverage: ["tone", "nearest", "blend"],
    target: engineTargets.colorMatch,
    userAction: "Select each option of the Match segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the colour diffusion switch",
    browser: controlBrowser("browser: diffusion mixes neighbouring inks"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Matching error spreads into neighbouring cells, so the boundary between two inks becomes a mixed gradient instead of a hard edge.",
    fixture: "one uploaded colour image matched to several inks",
    id: "palette.diffuse",
    kind: "control",
    target: engineTargets.colorDiffuse,
    userAction: "Set Match to Nearest and turn Diffuse on.",
  },
];
