/** Acceptance rows for the view and runtime surfaces: camera, glitch, motion timing, persistence, export, timeline and Infinity. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { appSchema } from "../app-schema";
import { engineTargets } from "../engine/engine-settings";
import { controlBrowser, outputBrowser } from "./acceptance-browser";

const persistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

export const viewAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "declares the camera view selector",
    browser: controlBrowser("browser: 3D view puts the sheet on a projected plane"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Flat draws the grid axis-aligned; 3D projects it onto a plane that converges toward a vanishing point and reveals the camera properties.",
    fixture: "wordmark source at default settings",
    id: "camera.projection",
    kind: "control",
    optionCoverage: ["flat", "perspective"],
    target: "camera.projection",
    userAction: "Select each option of the View segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the camera.tilt control",
    browser: controlBrowser("browser: tilt rotates the plane about its horizontal axis"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Tilt leans the plane away so marks toward the top shrink and converge.",
    fixture: "wordmark source with the 3D view selected",
    id: "camera.tilt",
    kind: "control",
    target: "camera.tilt",
    timelineCoverage: "keyframes",
    userAction: "Move Tilt away from zero in 3D view.",
  },
  {
    automated: true,
    automatedTestName: "declares the camera.pan control",
    browser: controlBrowser("browser: pan rotates the plane about its vertical axis"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Changing Pan swings the plane sideways so one edge recedes toward a vanishing point.",
    fixture: "wordmark source with the 3D view selected",
    id: "camera.pan",
    kind: "control",
    target: "camera.pan",
    timelineCoverage: "keyframes",
    userAction: "Move Pan away from zero in 3D view.",
  },
  {
    automated: true,
    automatedTestName: "declares the camera.roll control",
    browser: controlBrowser("browser: roll spins the plane within itself"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Changing Roll rotates the whole sheet in its own plane before projection.",
    fixture: "wordmark source with the 3D view selected",
    id: "camera.roll",
    kind: "control",
    target: "camera.roll",
    timelineCoverage: "keyframes",
    userAction: "Move Roll away from zero in 3D view.",
  },
  {
    automated: true,
    automatedTestName: "declares the camera.distance control",
    browser: controlBrowser("browser: distance pulls the camera back from the plane"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Distance frames more of the tilted plane; lowering it pushes in.",
    fixture: "wordmark source with the 3D view selected",
    id: "camera.distance",
    kind: "control",
    target: "camera.distance",
    timelineCoverage: "keyframes",
    userAction: "Change Distance in 3D view.",
  },
  {
    automated: true,
    automatedTestName: "declares the camera.fov control",
    browser: controlBrowser("browser: field of view changes how hard the plane converges"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "A wider field of view makes the plane converge harder toward its vanishing point.",
    fixture: "wordmark source with the 3D view selected",
    id: "camera.fov",
    kind: "control",
    target: "camera.fov",
    timelineCoverage: "keyframes",
    userAction: "Change Field of view in 3D view with a non-zero tilt.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch switch",
    browser: controlBrowser("browser: glitch tears the sheet and turns fully off"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "On displaces bands and blocks of the sheet and reveals the glitch settings; off restores the untouched sheet exactly.",
    fixture: "wordmark source at default settings",
    id: "glitch.enabled",
    kind: "control",
    target: "glitch.enabled",
    userAction: "Turn Glitch on, then off again.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch.amount control",
    browser: controlBrowser("browser: glitch amount scales every displacement"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Amount widens slice shifts, block offsets and channel fringes together.",
    fixture: "wordmark source with glitch on",
    id: "glitch.amount",
    kind: "control",
    target: "glitch.amount",
    timelineCoverage: "keyframes",
    userAction: "Move Amount with glitch on.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch.blocks control",
    browser: controlBrowser("browser: blocks smear rectangles from elsewhere on the sheet"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Each added block redraws a rectangle of cells with content from another part of the sheet.",
    fixture: "wordmark source with glitch on",
    id: "glitch.blocks",
    kind: "control",
    target: "glitch.blocks",
    timelineCoverage: "keyframes",
    userAction: "Raise Blocks with glitch on.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch.density control",
    browser: controlBrowser("browser: tear density decides how many bands shift"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Tear density makes more horizontal bands shift sideways.",
    fixture: "wordmark source with glitch on",
    id: "glitch.density",
    kind: "control",
    target: "glitch.density",
    timelineCoverage: "keyframes",
    userAction: "Raise Tear density with glitch on.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch.rate control",
    browser: controlBrowser("browser: glitch rate changes how often the tear redraws"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "A higher rate redraws the displacement more often across one loop; a lower rate holds each tear longer.",
    fixture: "wordmark source with glitch on",
    id: "glitch.rate",
    kind: "control",
    target: "glitch.rate",
    timelineCoverage: "keyframes",
    userAction: "Change Rate with glitch on and play the timeline.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch.slice control",
    browser: controlBrowser("browser: slice height sets the torn band thickness"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "A larger slice height tears thicker horizontal bands.",
    fixture: "wordmark source with glitch on",
    id: "glitch.slice",
    kind: "control",
    target: "glitch.slice",
    timelineCoverage: "keyframes",
    userAction: "Raise Slice height with glitch on.",
  },
  {
    automated: true,
    automatedTestName: "declares the glitch.split control",
    browser: controlBrowser("browser: channel split fringes the marks red and cyan"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Raising Channel split draws offset red and cyan copies behind the marks.",
    fixture: "wordmark source with glitch on",
    id: "glitch.split",
    kind: "control",
    target: "glitch.split",
    timelineCoverage: "keyframes",
    userAction: "Raise Channel split with glitch on.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion cycles slider",
    browser: controlBrowser("browser: cycles repeats the motion inside one loop"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "Raising Cycles repeats the motion that many whole times inside one timeline loop, so the loop stays seamless.",
    fixture: "wordmark source with pulse motion",
    id: "motion.cycles",
    kind: "control",
    target: engineTargets.motionCycles,
    timelineCoverage: "keyframes",
    userAction: "Select a motion style, raise Cycles and play the timeline.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion direction slider",
    browser: controlBrowser("browser: direction turns the line the motion travels along"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "For travelling styles, changing Direction turns the line the wave, sweep or reveal moves along.",
    fixture: "wordmark source with wave motion",
    id: "motion.direction",
    kind: "control",
    target: engineTargets.motionDirection,
    timelineCoverage: "keyframes",
    userAction: "Select Wave and change Direction.",
  },
  {
    automated: true,
    automatedTestName: "declares production reload coverage for the product schema",
    browser: {
      budget: "extended-io",
      file: "e2e/app-persistence.spec.ts",
      testName:
        "browser: app restores exact canvas, values, media, and panel workspace slices after reload",
    },
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, edited control values, the uploaded source, and the moved and collapsed Controls workspace remain visibly restored after a real browser reload.",
    fixture: "edited product workspace with one uploaded source",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices,
    target: engineTargets.cell,
    userAction:
      "Edit Cell size and zoom, upload a source, move and collapse Controls, wait for persistence, and reload the page.",
  },
  {
    automated: true,
    automatedTestName: "declares selected backing pixels for the raster preview",
    browser: {
      budget: "standard",
      file: "e2e/app-output.spec.ts",
      testName:
        "browser: render scale keeps selected backing pixels in every state",
    },
    componentType: "runtime",
    evidence: "rendered-pixels",
    expectedObservable:
      "The preview canvas keeps CSS size stable while its backing pixels equal CSS size multiplied by device pixel ratio and the selected Resolution scale, during interaction, at rest, and during playback.",
    fixture: "wordmark source with pulse motion",
    id: "canvas.render-scale",
    kind: "runtime",
    renderScaleCoverage: {
      kind: "selected-backing-pixels",
      states: ["interaction", "playback", "steady"],
    },
    target: "canvas.renderScale",
    userAction:
      "Drag Cell size, let the canvas settle, then play the timeline at the selected Resolution scale.",
  },
  {
    automated: true,
    automatedTestName: "declares the image export format selector",
    browser: outputBrowser("browser: export format downloads the selected type"),
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "The sticky action follows the selected format and downloads a decodable artifact of that type.",
    fixture: "wordmark source at default settings",
    id: "export.image.format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select each Format option and export.",
  },
  {
    automated: true,
    automatedTestName: "declares the image export resolution selector",
    browser: outputBrowser(
      "browser: export resolution produces the selected long edge",
    ),
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "The exported still's long edge matches the selected 2K, 4K or 8K resolution.",
    fixture: "wordmark source at default settings",
    id: "export.image.resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select each Resolution option and export.",
  },
  {
    automated: true,
    automatedTestName: "declares the video export format selector",
    browser: outputBrowser("browser: video format encodes the selected container"),
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "The sticky video action follows the selected container and downloads a decodable file of that type.",
    fixture: "wordmark source with pulse motion",
    id: "export.video.format",
    kind: "control",
    optionCoverage: ["mp4", "webm"],
    target: "export.video.format",
    userAction: "Select each video Format option and export.",
  },
  {
    automated: true,
    automatedTestName: "declares the video export resolution selector",
    browser: outputBrowser(
      "browser: video resolution encodes the selected dimensions",
    ),
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "The encoded video dimensions follow the selected Current or 4K resolution.",
    fixture: "wordmark source with pulse motion",
    id: "export.video.resolution",
    kind: "control",
    optionCoverage: ["current", "4k"],
    target: "export.video.resolution",
    userAction: "Select each video Resolution option and export.",
  },
  {
    actionCoverage: ["export.png", "export.video"],
    automated: true,
    automatedTestName: "declares the sticky export actions",
    browser: outputBrowser("browser: export actions download the halftone sheet and its loop"),
    componentType: "panelActions",
    evidence: "exported-bytes",
    exportArtifactCoverage: [
      "all-required-image-export-behavior",
      "all-required-video-export-behavior",
    ],
    expectedObservable:
      "Export PNG downloads a decodable still whose pixels match the visible sheet, and Export MP4 encodes the timeline at a fixed 30 FPS schedule into a decodable video whose frames change across its duration.",
    fixture: "wordmark source with pulse motion",
    id: "actions.output",
    kind: "control",
    target: "actions.output",
    userAction: "Press Export PNG, then press Export MP4.",
  },
  {
    automated: true,
    automatedTestName: "declares infinity scene bounds for still export",
    browser: outputBrowser(
      "browser: infinity still export covers the visible composition bounds",
    ),
    componentType: "canvas-mode",
    evidence: "exported-bytes",
    expectedObservable:
      "With Infinity canvas on, the exported still covers the complete visible sheet bounds with the selected background and decodable content.",
    fixture: "wordmark source at default settings",
    id: "canvas.infinity-image-export",
    infinityCanvasCoverage: "scene-bounds-image-export",
    kind: "runtime",
    target: "export.image.format",
    userAction: "Turn Infinity canvas on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares infinity scene bounds for video export",
    browser: outputBrowser(
      "browser: infinity video export keeps the saved artboard dimensions",
    ),
    componentType: "canvas-mode",
    evidence: "exported-bytes",
    expectedObservable:
      "With Infinity canvas on, the exported video keeps the saved finite artboard dimensions, its timeline duration, and decodable changing frames.",
    fixture: "wordmark source with pulse motion",
    id: "canvas.infinity-video-export",
    infinityCanvasCoverage: "scene-bounds-video-export",
    kind: "runtime",
    target: "export.video.format",
    userAction: "Turn Infinity canvas on and export a video.",
  },
  {
    automated: true,
    automatedTestName: "declares the runtime keyframe timeline surface",
    browser: {
      budget: "standard",
      file: "e2e/app-output.spec.ts",
      testName:
        "browser: keyframe rows, diamonds and evaluation drive the halftone sheet",
    },
    componentType: "timeline",
    evidence: "timeline-output",
    expectedObservable:
      "Expanding the timeline shows keyframe rows; a parameter diamond adds a keyframe, editing at another time updates that track, and moving the playhead between them redraws the sheet from the evaluated values while procedural motion keeps looping on top.",
    fixture: "wordmark source with one keyframed camera tilt",
    id: "timeline.keyframes",
    kind: "runtime",
    target: "panels.timeline.extended",
    timelineCoverage: "keyframes",
    userAction:
      "Expand the timeline, add a keyframe on Tilt, scrub to another time, change Tilt, then scrub between the two keyframes.",
  },
  {
    automated: true,
    automatedTestName: "declares seamless forward playback for the animated sheet",
    browser: {
      budget: "standard",
      file: "e2e/app-output.spec.ts",
      testName:
        "browser: playback loops forward and the first and last frames stitch",
    },
    componentType: "timeline",
    evidence: "timeline-output",
    expectedObservable:
      "Playback advances forward only, scrubbing and pausing change the drawn frame, the first and last frames match, and editing duration keeps the loop seamless.",
    fixture: "wordmark source with pulse motion",
    id: "timeline.playback",
    kind: "runtime",
    target: "panels.timeline.extended",
    timelineCoverage: "playback",
    timelineLoopProof: {
      direction: "forward-only",
      durationChange: "reproved-after-edit",
      reversePlayback: "forbidden",
      seam: "first-last-match",
    },
    timelinePlaybackCoverage: "all-playback-behavior",
    userAction:
      "Play, scrub, pause, compare the first and last frames, then edit the duration and recheck.",
  },
  {
    automated: true,
    automatedTestName: "declares infinity mode continuity for the sheet",
    browser: {
      budget: "standard",
      file: "e2e/app-output.spec.ts",
      testName:
        "browser: infinity canvas preserves the sheet and restores the artboard",
    },
    componentType: "canvas-mode",
    evidence: "viewport-side-effect",
    expectedObservable:
      "Turning Infinity canvas on removes only the artboard boundary and size controls; the sheet keeps its world frame, renderer identity and backing, and turning it off restores the exact dormant finite size without recentring.",
    fixture: "wordmark source at default settings",
    id: "canvas.infinity",
    infinityCanvasCoverage: "mode-continuity-and-restoration",
    kind: "runtime",
    target: "canvas.infinity",
    userAction: "Toggle Infinity canvas on and back off.",
  },
];
