/** Acceptance rows for colour and hand editing: palette, brush, painting, guides, patterns, mixing and matching. */

import type { ToolcraftComponentAcceptance } from "../acceptance/types";
import { engineTargets } from "../engine/engine-settings";
import { controlBrowser, renderBrowser } from "./acceptance-browser";

export const editingAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "declares the editable brand ink list",
    browser: controlBrowser("browser: ink entries colour the tone bands"),
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "product-output",
    expectedObservable:
      "Ink is quantized across the entries in order, so editing, adding or removing an ink changes the colours drawn on the sheet.",
    fixture: "wordmark source at default settings",
    id: "palette.inks",
    kind: "control",
    target: engineTargets.inks,
    userAction: "Edit an ink, add one, then remove the last entry.",
  },
  {
    automated: true,
    automatedTestName: "declares the palette mode selector",
    browser: controlBrowser("browser: palette mode switches ink source"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Inks quantizes to the brand list and shows it; Source keeps each sampled pixel colour and hides the list.",
    fixture: "one uploaded colour image",
    id: "palette.mode",
    kind: "control",
    optionCoverage: ["full", "inks", "source"],
    target: engineTargets.paletteMode,
    userAction: "Select each option of the Color segmented control.",
  },
  {
    actionCoverage: ["palette.shuffle"],
    automated: true,
    automatedTestName: "declares the ink shuffle command",
    browser: controlBrowser(
      "browser: shuffle reorders the ink list and the sheet",
    ),
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable:
      "Shuffle reorders the ink entries, so the tone bands take different colours.",
    fixture: "wordmark source with three inks",
    id: "palette.shuffle",
    kind: "control",
    target: "palette.shuffle",
    userAction: "Press Shuffle with three or more inks.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion amount slider",
    browser: controlBrowser("browser: motion amount scales the animated offset"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "With a motion style selected, Amount scales how far each unit departs from its still size.",
    fixture: "wordmark source with pulse motion",
    id: "motion.amount",
    kind: "control",
    target: engineTargets.motionAmount,
    timelineCoverage: "keyframes",
    userAction: "Select a motion style and move Amount.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion stagger slider",
    browser: controlBrowser("browser: stagger delays units across the grid"),
    componentType: "slider",
    evidence: "timeline-output",
    expectedObservable:
      "Raising Stagger delays each unit by its distance from the top-left corner, so the cycle travels across the sheet.",
    fixture: "wordmark source with pulse motion",
    id: "motion.stagger",
    kind: "control",
    target: engineTargets.motionStagger,
    timelineCoverage: "keyframes",
    userAction: "Select a motion style and move Stagger.",
  },
  {
    automated: true,
    automatedTestName: "declares the motion style selector",
    browser: controlBrowser("browser: every motion style animates its own way"),
    componentType: "select",
    evidence: "timeline-output",
    expectedObservable:
      "Still leaves the sheet fixed and hides the motion settings; each of the sixteen animated styles moves the units its own way, and the travelling styles also reveal Direction.",
    fixture: "wordmark source at default settings",
    id: "motion.style",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: engineTargets.motionStyle,
    userAction: "Select each option of the Motion select.",
  },
  {
    automated: true,
    automatedTestName: "declares the brush mode selector",
    browser: controlBrowser("browser: brush mode switches painting between ink and erase"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Draw paints cells in the drawing ink and reveals it; Eraser clears cells, including generated ones, and hides the ink control.",
    fixture: "wordmark source with painted cells",
    id: "tool.brush",
    kind: "control",
    optionCoverage: ["draw", "erase"],
    target: engineTargets.brush,
    userAction: "Select each option of the Brush segmented control and paint.",
  },
  {
    automated: true,
    automatedTestName: "declares the drawing ink control",
    browser: controlBrowser("browser: drawing ink colours newly painted cells"),
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Cells painted after the change take the selected ink.",
    fixture: "wordmark source with painted cells",
    id: "tool.color",
    interactionId: "brush-properties",
    kind: "control",
    target: engineTargets.drawColor,
    timelineCoverage: "keyframes",
    userAction: "Change Ink, then paint on the canvas.",
  },
  {
    automated: true,
    automatedTestName: "declares the brush size slider",
    browser: controlBrowser("browser: brush size widens the painted footprint"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "A larger brush size paints a wider square block of cells per stroke.",
    fixture: "wordmark source with painted cells",
    id: "tool.size",
    kind: "control",
    target: engineTargets.brushSize,
    timelineCoverage: "keyframes",
    userAction: "Raise Brush size and paint one stroke.",
  },
  {
    automated: true,
    automatedTestName: "declares canvas painting as a canvas-owned operation",
    browser: controlBrowser("browser: dragging on the canvas paints a continuous run of cells"),
    canvasHandle: {
      outputObservable:
        "The dragged cells take the drawing ink immediately and remain after the pointer releases.",
      testId: "syntax-error-output",
      writesTarget: "controls.setValue",
    },
    componentType: "canvas-paint",
    evidence: "product-output",
    expectedObservable:
      "Pressing and dragging paints every cell along the path, Shift extends a straight run from the previous cell, and one stroke is one undoable step.",
    fixture: "wordmark source at default settings",
    id: "canvas.paint",
    interactionId: "cell-paint",
    kind: "canvas-handle",
    target: "controls.setValue",
    userAction: "Drag across the canvas, then Shift-click away from the stroke, then undo.",
  },
  {
    automated: true,
    automatedTestName: "declares the cell grid guide",
    browser: renderBrowser("browser: cell grid draws guides that stay out of exports"),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "The grid guide appears over the sheet in preview and is absent from an exported still.",
    fixture: "wordmark source at default settings",
    id: "view.grid",
    kind: "control",
    target: engineTargets.gridOverlay,
    userAction: "Turn Cell grid on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares the circle guide",
    browser: renderBrowser("browser: circle guide draws a guide that stays out of exports"),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "The circular guide appears over the sheet in preview and is absent from an exported still.",
    fixture: "wordmark source at default settings",
    id: "view.circle",
    kind: "control",
    target: engineTargets.circleOverlay,
    userAction: "Turn Circle guide on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares the pattern selector",
    browser: controlBrowser("browser: every pattern stamps its own arrangement"),
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Checker, Stripe, Dots, Noise and Ramp each fill the sheet with a distinct arrangement of painted cells.",
    fixture: "wordmark source at default settings",
    id: "pattern.kind",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: engineTargets.patternKind,
    userAction: "Select each Pattern option and press Fill canvas.",
  },
  {
    automated: true,
    automatedTestName: "declares the pattern scale slider",
    browser: controlBrowser("browser: pattern scale changes the stamped period"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "A larger scale produces coarser pattern blocks across the same grid.",
    fixture: "wordmark source at default settings",
    id: "pattern.scale",
    kind: "control",
    target: engineTargets.patternScale,
    timelineCoverage: "keyframes",
    userAction: "Change Scale and press Fill canvas.",
  },
  {
    automated: true,
    automatedTestName: "declares the pattern angle slider",
    browser: controlBrowser("browser: pattern angle rotates the stamped arrangement"),
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Changing Angle rotates the stamped pattern across the sheet.",
    fixture: "wordmark source at default settings",
    id: "pattern.angle",
    kind: "control",
    target: engineTargets.patternAngle,
    timelineCoverage: "keyframes",
    userAction: "Change Angle and press Fill canvas.",
  },
  {
    actionCoverage: ["pattern.fill"],
    automated: true,
    automatedTestName: "declares the pattern fill command",
    browser: controlBrowser("browser: fill canvas stamps the pattern into painted cells"),
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable:
      "Fill canvas writes the selected pattern into the painted layer across the whole sheet.",
    fixture: "wordmark source at default settings",
    id: "pattern.fill",
    kind: "control",
    target: "pattern.fill",
    userAction: "Press Fill canvas.",
  },
  {
    actionCoverage: ["pattern.clear"],
    automated: true,
    automatedTestName: "declares the clear painted command",
    browser: controlBrowser("browser: clear painted removes every painted cell"),
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable:
      "Clear painted drops every painted cell and leaves the generated sheet alone.",
    fixture: "wordmark source with painted cells",
    id: "pattern.clear",
    kind: "control",
    target: "pattern.clear",
    userAction: "Paint some cells, then press Clear painted.",
  },
  {
    automated: true,
    automatedTestName: "declares the greyscale palette switch",
    browser: controlBrowser("browser: greyscale converts every drawn ink to luma"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Every unit, generated or painted, is drawn at its perceptual luma instead of its colour.",
    fixture: "wordmark source at default settings",
    id: "palette.greyscale",
    kind: "control",
    target: engineTargets.greyscale,
    userAction: "Turn Greyscale on.",
  },
  {
    actionCoverage: ["palette.remap"],
    automated: true,
    automatedTestName: "declares the artwork remap command",
    browser: controlBrowser("browser: remap snaps painted cells onto the ink list"),
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable:
      "Every painted cell changes to its closest ink from the current list.",
    fixture: "wordmark source with painted cells outside the ink list",
    id: "palette.remap",
    kind: "control",
    target: "palette.remap",
    userAction: "Paint with an off-palette ink, change the ink list, then press Remap painted art.",
  },
  {
    automated: true,
    automatedTestName: "declares the flat ink export switch",
    browser: renderBrowser("browser: flat ink draws every unit in one colour"),
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Every unit is drawn in the first ink instead of its own colour, in preview and in the exported still.",
    fixture: "wordmark source with a multi-ink palette",
    id: "output.flat-ink",
    kind: "control",
    target: engineTargets.ignoreColor,
    userAction: "Turn Flat ink on export on and export a still.",
  },
  {
    automated: true,
    automatedTestName: "declares the editable mark mix",
    browser: controlBrowser("browser: a mix draws every chosen mark on one sheet"),
    componentType: "collectionActions",
    controlPartCoverage: [
      "collectionActions.add",
      "collectionActions.items",
      "collectionActions.remove",
    ],
    evidence: "product-output",
    expectedObservable:
      "With Shape set to Mix, every entry appears somewhere on the sheet, so a square and a glyph are drawn together; repeating an entry makes it more common.",
    fixture: "one uploaded source image with Shape set to Mix",
    id: "unit.mix",
    kind: "control",
    target: engineTargets.mix,
    userAction: "Set Shape to Mix, add a Glyph entry beside Square, then remove the last entry.",
  },
  {
    automated: true,
    automatedTestName: "declares the mix spread selector",
    browser: controlBrowser("browser: spread changes how the mix is distributed"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Random scatters the marks, Cycle alternates them in reading order, and Tone assigns them by cell brightness.",
    fixture: "one uploaded source image with Shape set to Mix",
    id: "unit.mix-order",
    kind: "control",
    optionCoverage: ["random", "cycle", "tone"],
    target: engineTargets.mixDistribution,
    userAction: "Select each option of the Spread segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the colour match selector",
    browser: controlBrowser("browser: colour match changes how inks are assigned"),
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Tone bands the sheet by brightness, Nearest gives each cell its closest ink so separate hues stay separate, and Blend weights the two closest inks.",
    fixture: "one uploaded colour image with several inks",
    id: "palette.match",
    kind: "control",
    optionCoverage: ["tone", "nearest", "blend"],
    target: engineTargets.colorMatch,
    userAction: "Select each option of the Match segmented control.",
  },
  {
    automated: true,
    automatedTestName: "declares the colour diffusion switch",
    browser: controlBrowser("browser: diffusion mixes neighbouring inks"),
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Matching error spreads into neighbouring cells, so the boundary between two inks becomes a mixed gradient instead of a hard edge.",
    fixture: "one uploaded colour image matched to several inks",
    id: "palette.diffuse",
    kind: "control",
    target: engineTargets.colorDiffuse,
    userAction: "Set Match to Nearest and turn Diffuse on.",
  },
];
